/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "AddTxProfile.h"

static int
memb_radio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_immediateAccess_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_radio_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_memb_immediateAccess_constr_7 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
asn_TYPE_member_t asn_MBR_AddTxProfile_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AddTxProfile, radio),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ &asn_OER_memb_radio_constr_2, 0,  memb_radio_constraint_1 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AddTxProfile, channelIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelNumber80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AddTxProfile, timeslot),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeSlot,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeslot"
		},
	{ ATF_POINTER, 3, offsetof(struct AddTxProfile, operationalRateSet),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"operationalRateSet"
		},
	{ ATF_POINTER, 2, offsetof(struct AddTxProfile, edcaParameterSet),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EdcaParameterSet,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"edcaParameterSet"
		},
	{ ATF_POINTER, 1, offsetof(struct AddTxProfile, immediateAccess),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_immediateAccess_constr_7, 0,  memb_immediateAccess_constraint_1 },
		0, 0, /* No default value */
		"immediateAccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AddTxProfile, adaptable),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"adaptable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AddTxProfile, transmitPowerLevel),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TXpower80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transmitPowerLevel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AddTxProfile, dataRate),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataRate80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataRate"
		},
};
static const int asn_MAP_AddTxProfile_oms_1[] = { 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_AddTxProfile_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AddTxProfile_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* channelIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* timeslot */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* operationalRateSet */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* edcaParameterSet */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* immediateAccess */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* adaptable */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* transmitPowerLevel */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* dataRate */
};
asn_SEQUENCE_specifics_t asn_SPC_AddTxProfile_specs_1 = {
	sizeof(struct AddTxProfile),
	offsetof(struct AddTxProfile, _asn_ctx),
	asn_MAP_AddTxProfile_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_AddTxProfile_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AddTxProfile = {
	"AddTxProfile",
	"AddTxProfile",
	&asn_OP_SEQUENCE,
	asn_DEF_AddTxProfile_tags_1,
	sizeof(asn_DEF_AddTxProfile_tags_1)
		/sizeof(asn_DEF_AddTxProfile_tags_1[0]), /* 1 */
	asn_DEF_AddTxProfile_tags_1,	/* Same as above */
	sizeof(asn_DEF_AddTxProfile_tags_1)
		/sizeof(asn_DEF_AddTxProfile_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AddTxProfile_1,
	9,	/* Elements count */
	&asn_SPC_AddTxProfile_specs_1	/* Additional specs */
};

