/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_AddTxProfile_H_
#define	_AddTxProfile_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include "ChannelNumber80211.h"
#include "TimeSlot.h"
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include "TXpower80211.h"
#include "DataRate80211.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EdcaParameterSet;

/* AddTxProfile */
typedef struct AddTxProfile {
	RadioInterface_t	 radio;
	ChannelNumber80211_t	 channelIdentifier;
	TimeSlot_t	 timeslot;
	OCTET_STRING_t	*operationalRateSet	/* OPTIONAL */;
	struct EdcaParameterSet	*edcaParameterSet	/* OPTIONAL */;
	long	*immediateAccess	/* OPTIONAL */;
	BOOLEAN_t	 adaptable;
	TXpower80211_t	 transmitPowerLevel;
	DataRate80211_t	 dataRate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AddTxProfile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddTxProfile;
extern asn_SEQUENCE_specifics_t asn_SPC_AddTxProfile_specs_1;
extern asn_TYPE_member_t asn_MBR_AddTxProfile_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EdcaParameterSet.h"

#endif	/* _AddTxProfile_H_ */
#include <asn_internal.h>
