/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_AddUserService_H_
#define	_AddUserService_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Psid.h"
#include "RadioInterface.h"
#include "UserRequestType.h"
#include "WsaType.h"
#include "ChannelNumber80211.h"
#include "MACaddress.h"
#include "AdvertiserIdentifier.h"
#include <INTEGER.h>
#include <NativeInteger.h>
#include "TimeSlot.h"
#include "EventHandling.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProviderServiceContext;

/* AddUserService */
typedef struct AddUserService {
	Psid_t	 psid;
	RadioInterface_t	 radio;
	UserRequestType_t	 userRequestType;
	WsaType_t	 wsaType;
	struct ProviderServiceContext	*providerServiceContext	/* OPTIONAL */;
	ChannelNumber80211_t	*channelIdentifier	/* OPTIONAL */;
	MACaddress_t	*sourceMACAddr	/* OPTIONAL */;
	AdvertiserIdentifier_t	*advertiserId	/* OPTIONAL */;
	INTEGER_t	*linkQuality	/* OPTIONAL */;
	long	*immediateAccess	/* OPTIONAL */;
	ChannelNumber80211_t	*wsaChannelIdentifier	/* OPTIONAL */;
	TimeSlot_t	*channelAccess	/* OPTIONAL */;
	EventHandling_t	 eventHandling;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AddUserService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AddUserService;
extern asn_SEQUENCE_specifics_t asn_SPC_AddUserService_specs_1;
extern asn_TYPE_member_t asn_MBR_AddUserService_1[13];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProviderServiceContext.h"

#endif	/* _AddUserService_H_ */
#include <asn_internal.h>
