/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Antenna_H_
#define	_Antenna_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Antenna {
	Antenna_antenna1	= 1,
	Antenna_antenna2	= 2,
	Antenna_both	= 3
} e_Antenna;

/* Antenna */
typedef ENUMERATED_t	 Antenna_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Antenna;
extern const asn_INTEGER_specifics_t asn_SPC_Antenna_specs_1;
asn_struct_free_f Antenna_free;
asn_struct_print_f Antenna_print;
asn_constr_check_f Antenna_constraint;
ber_type_decoder_f Antenna_decode_ber;
der_type_encoder_f Antenna_encode_der;
xer_type_decoder_f Antenna_decode_xer;
xer_type_encoder_f Antenna_encode_xer;
oer_type_decoder_f Antenna_decode_oer;
oer_type_encoder_f Antenna_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Antenna_H_ */
#include <asn_internal.h>
