/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Antenna.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Antenna_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_Antenna_value2enum_1[] = {
	{ 1,	8,	"antenna1" },
	{ 2,	8,	"antenna2" },
	{ 3,	4,	"both" }
};
static const unsigned int asn_MAP_Antenna_enum2value_1[] = {
	0,	/* antenna1(1) */
	1,	/* antenna2(2) */
	2	/* both(3) */
};
const asn_INTEGER_specifics_t asn_SPC_Antenna_specs_1 = {
	asn_MAP_Antenna_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_Antenna_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_Antenna_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Antenna = {
	"Antenna",
	"Antenna",
	&asn_OP_ENUMERATED,
	asn_DEF_Antenna_tags_1,
	sizeof(asn_DEF_Antenna_tags_1)
		/sizeof(asn_DEF_Antenna_tags_1[0]), /* 1 */
	asn_DEF_Antenna_tags_1,	/* Same as above */
	sizeof(asn_DEF_Antenna_tags_1)
		/sizeof(asn_DEF_Antenna_tags_1[0]), /* 1 */
	{ &asn_OER_type_Antenna_constr_1, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_Antenna_specs_1	/* Additional specs */
};

