/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ChannelOptions_H_
#define	_ChannelOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MandApp.h"
#include "ReplyAddress.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceInfoExts;

/* ChannelOptions */
typedef struct ChannelOptions {
	MandApp_t	*mandApp	/* OPTIONAL */;
	ReplyAddress_t	*serviceProviderPort	/* OPTIONAL */;
	struct ServiceInfoExts	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChannelOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelOptions;
extern asn_SEQUENCE_specifics_t asn_SPC_ChannelOptions_specs_1;
extern asn_TYPE_member_t asn_MBR_ChannelOptions_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceInfoExts.h"

#endif	/* _ChannelOptions_H_ */
#include <asn_internal.h>
