/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ChangeWsaProviderService_H_
#define	_ChangeWsaProviderService_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include "WsmServiceInfos.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChangeWsaProviderService */
typedef struct ChangeWsaProviderService {
	RadioInterface_t	 radio;
	WsmServiceInfos_t	 serviceInfos;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChangeWsaProviderService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChangeWsaProviderService;
extern asn_SEQUENCE_specifics_t asn_SPC_ChangeWsaProviderService_specs_1;
extern asn_TYPE_member_t asn_MBR_ChangeWsaProviderService_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ChangeWsaProviderService_H_ */
#include <asn_internal.h>
