/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ChannelInfoExt_H_
#define	_ChannelInfoExt_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Extension.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ChannelInfoExt */
typedef Extension_73P0_t	 ChannelInfoExt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelInfoExt;
asn_struct_free_f ChannelInfoExt_free;
asn_struct_print_f ChannelInfoExt_print;
asn_constr_check_f ChannelInfoExt_constraint;
ber_type_decoder_f ChannelInfoExt_decode_ber;
der_type_encoder_f ChannelInfoExt_encode_der;
xer_type_decoder_f ChannelInfoExt_decode_xer;
xer_type_encoder_f ChannelInfoExt_encode_xer;
oer_type_decoder_f ChannelInfoExt_decode_oer;
oer_type_encoder_f ChannelInfoExt_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelInfoExt_H_ */
#include <asn_internal.h>
