/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ContentType_H_
#define	_ContentType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ContentType {
	ContentType_mOther	= 0,
	ContentType_mIeee16092Data	= 1,
	ContentType_mWSA	= 2,
	ContentType_mBSM	= 3,
	ContentType_mMAP	= 4,
	ContentType_mSPAT	= 5,
	ContentType_mTIM	= 6
} e_ContentType;

/* ContentType */
typedef ENUMERATED_t	 ContentType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentType;
extern const asn_INTEGER_specifics_t asn_SPC_ContentType_specs_1;
asn_struct_free_f ContentType_free;
asn_struct_print_f ContentType_print;
asn_constr_check_f ContentType_constraint;
ber_type_decoder_f ContentType_decode_ber;
der_type_encoder_f ContentType_encode_der;
xer_type_decoder_f ContentType_decode_xer;
xer_type_encoder_f ContentType_encode_xer;
oer_type_decoder_f ContentType_decode_oer;
oer_type_encoder_f ContentType_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentType_H_ */
#include <asn_internal.h>
