/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "D2945Request.h"

static const long asn_VAL_1_setInitialState = 1;
static const long asn_VAL_2_startBsmTx = 3;
static const long asn_VAL_3_stopBsmTx = 4;
static const long asn_VAL_4_enableCongestionMitigation = 5;
static const long asn_VAL_5_setTemporaryID = 6;
static const long asn_VAL_6_setTransmissionState = 11;
static const long asn_VAL_7_setSteeringWheelAngle = 14;
static const long asn_VAL_8_setBrakeSystemStatus = 16;
static const long asn_VAL_9_setVehicleSize = 17;
static const long asn_VAL_10_setExteriorLights = 18;
static const long asn_VAL_11_setVehicleEventFlags = 19;
static const long asn_VAL_12_startBsmRx = 20;
static const long asn_VAL_13_stopBsmRx = 21;
static const long asn_VAL_14_d2945EnableGpsInput = 2;
static const long asn_VAL_15_d2945SetLatitude = 7;
static const long asn_VAL_16_d2945SetLongitude = 8;
static const long asn_VAL_17_d2945SetElevation = 9;
static const long asn_VAL_18_d2945SetPositionalAccuracy = 10;
static const long asn_VAL_19_d2945SetSpeed = 12;
static const long asn_VAL_20_d2945SetHeading = 13;
static const long asn_VAL_21_d2945SetAccelerationSet4Way = 15;
static const long asn_VAL_22_d2945SetGpsTime = 22;
static const asn_ioc_cell_t asn_IOS_D2945MessageTypes_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_1_setInitialState },
	{ "&Type", aioc__type, &asn_DEF_SetInitialState },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_2_startBsmTx },
	{ "&Type", aioc__type, &asn_DEF_StartBsmTx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_3_stopBsmTx },
	{ "&Type", aioc__type, &asn_DEF_StopBsmTx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_4_enableCongestionMitigation },
	{ "&Type", aioc__type, &asn_DEF_EnableCongestionMitigation },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_5_setTemporaryID },
	{ "&Type", aioc__type, &asn_DEF_SetTemporaryID },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_6_setTransmissionState },
	{ "&Type", aioc__type, &asn_DEF_SetTransmissionState },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_7_setSteeringWheelAngle },
	{ "&Type", aioc__type, &asn_DEF_SetSteeringWheelAngle },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_8_setBrakeSystemStatus },
	{ "&Type", aioc__type, &asn_DEF_SetBrakeSystemStatus },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_9_setVehicleSize },
	{ "&Type", aioc__type, &asn_DEF_SetVehicleSize },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_10_setExteriorLights },
	{ "&Type", aioc__type, &asn_DEF_SetExteriorLights },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_11_setVehicleEventFlags },
	{ "&Type", aioc__type, &asn_DEF_SetVehicleEventFlags },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_12_startBsmRx },
	{ "&Type", aioc__type, &asn_DEF_StartBsmRx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_13_stopBsmRx },
	{ "&Type", aioc__type, &asn_DEF_StopBsmRx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_14_d2945EnableGpsInput },
	{ "&Type", aioc__type, &asn_DEF_EnableGpsInput },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_15_d2945SetLatitude },
	{ "&Type", aioc__type, &asn_DEF_SetLatitude },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_16_d2945SetLongitude },
	{ "&Type", aioc__type, &asn_DEF_SetLongitude },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_17_d2945SetElevation },
	{ "&Type", aioc__type, &asn_DEF_SetElevation },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_18_d2945SetPositionalAccuracy },
	{ "&Type", aioc__type, &asn_DEF_SetPositionalAccuracy },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_19_d2945SetSpeed },
	{ "&Type", aioc__type, &asn_DEF_SetSpeed },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_20_d2945SetHeading },
	{ "&Type", aioc__type, &asn_DEF_SetHeading },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_21_d2945SetAccelerationSet4Way },
	{ "&Type", aioc__type, &asn_DEF_SetAccelerationSet4Way },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_22_d2945SetGpsTime },
	{ "&Type", aioc__type, &asn_DEF_SetGpsTime }
};
static const asn_ioc_set_t asn_IOS_D2945MessageTypes_1[] = {
	22, 2, asn_IOS_D2945MessageTypes_1_rows
};
static int
memb_messageId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_D2945Request_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_D2945MessageTypes_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Type */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct D2945Request, messageId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_messageId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_value_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_TYPE_member_t asn_MBR_value_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetInitialState),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_SetInitialState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetInitialState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.StartBsmTx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartBsmTx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartBsmTx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.StopBsmTx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopBsmTx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopBsmTx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.EnableCongestionMitigation),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_EnableCongestionMitigation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"EnableCongestionMitigation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetTemporaryID),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SetTemporaryID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetTemporaryID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetTransmissionState),
		(ASN_TAG_CLASS_UNIVERSAL | (10 << 2)),
		0,
		&asn_DEF_SetTransmissionState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetTransmissionState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetSteeringWheelAngle),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetSteeringWheelAngle,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetSteeringWheelAngle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetBrakeSystemStatus),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetBrakeSystemStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetBrakeSystemStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetVehicleSize),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetVehicleSize,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetVehicleSize"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetExteriorLights),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_SetExteriorLights,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetExteriorLights"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetVehicleEventFlags),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_SetVehicleEventFlags,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetVehicleEventFlags"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.StartBsmRx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartBsmRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartBsmRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.StopBsmRx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopBsmRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopBsmRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.EnableGpsInput),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_EnableGpsInput,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"EnableGpsInput"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetLatitude),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetLatitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetLatitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetLongitude),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetLongitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetLongitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetElevation),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetElevation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetElevation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetPositionalAccuracy),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetPositionalAccuracy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetPositionalAccuracy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetSpeed),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetSpeed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetHeading),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetHeading,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetHeading"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetAccelerationSet4Way),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetAccelerationSet4Way,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetAccelerationSet4Way"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request__value, choice.SetGpsTime),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetGpsTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetGpsTime"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 2 }, /* SetInitialState */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 3, -1, 1 }, /* EnableCongestionMitigation */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 13, -2, 0 }, /* EnableGpsInput */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, 0, 5 }, /* SetSteeringWheelAngle */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 15, -1, 4 }, /* SetLongitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 16, -2, 3 }, /* SetElevation */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 18, -3, 2 }, /* SetSpeed */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 19, -4, 1 }, /* SetHeading */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 21, -5, 0 }, /* SetGpsTime */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 9, 0, 1 }, /* SetExteriorLights */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 10, -1, 0 }, /* SetVehicleEventFlags */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, 0, 0 }, /* SetTemporaryID */
    { (ASN_TAG_CLASS_UNIVERSAL | (10 << 2)), 5, 0, 0 }, /* SetTransmissionState */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 8 }, /* StartBsmTx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 7 }, /* StopBsmTx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -2, 6 }, /* SetBrakeSystemStatus */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -3, 5 }, /* SetVehicleSize */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -4, 4 }, /* StartBsmRx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -5, 3 }, /* StopBsmRx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -6, 2 }, /* SetLatitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -7, 1 }, /* SetPositionalAccuracy */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -8, 0 } /* SetAccelerationSet4Way */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_3 = {
	sizeof(struct D2945Request__value),
	offsetof(struct D2945Request__value, _asn_ctx),
	offsetof(struct D2945Request__value, present),
	sizeof(((struct D2945Request__value *)0)->present),
	asn_MAP_value_tag2el_3,
	22,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_3 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_3,
	22,	/* Elements count */
	&asn_SPC_value_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_D2945Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct D2945Request, messageId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgID,
		0,
		{ &asn_OER_memb_messageId_constr_2, 0,  memb_messageId_constraint_1 },
		0, 0, /* No default value */
		"messageId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct D2945Request, value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_3,
		select_D2945Request_value_type,
		{ &asn_OER_memb_value_constr_3, 0,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_D2945Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_D2945Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* messageId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_D2945Request_specs_1 = {
	sizeof(struct D2945Request),
	offsetof(struct D2945Request, _asn_ctx),
	asn_MAP_D2945Request_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_D2945Request = {
	"D2945Request",
	"D2945Request",
	&asn_OP_SEQUENCE,
	asn_DEF_D2945Request_tags_1,
	sizeof(asn_DEF_D2945Request_tags_1)
		/sizeof(asn_DEF_D2945Request_tags_1[0]), /* 1 */
	asn_DEF_D2945Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_D2945Request_tags_1)
		/sizeof(asn_DEF_D2945Request_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_D2945Request_1,
	2,	/* Elements count */
	&asn_SPC_D2945Request_specs_1	/* Additional specs */
};

