/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_D2945Indication_H_
#define	_D2945Indication_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Indication.h"

#ifdef __cplusplus
extern "C" {
#endif

/* D2945Indication */
typedef Indication_t	 D2945Indication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_D2945Indication;
asn_struct_free_f D2945Indication_free;
asn_struct_print_f D2945Indication_print;
asn_constr_check_f D2945Indication_constraint;
ber_type_decoder_f D2945Indication_decode_ber;
der_type_encoder_f D2945Indication_encode_der;
xer_type_decoder_f D2945Indication_decode_xer;
xer_type_encoder_f D2945Indication_encode_xer;
oer_type_decoder_f D2945Indication_decode_oer;
oer_type_encoder_f D2945Indication_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _D2945Indication_H_ */
#include <asn_internal.h>
