/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_D2945Request_H_
#define	_D2945Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "SetInitialState.h"
#include "StartBsmTx.h"
#include "StopBsmTx.h"
#include "EnableCongestionMitigation.h"
#include "SetTemporaryID.h"
#include "SetTransmissionState.h"
#include "SetSteeringWheelAngle.h"
#include "SetBrakeSystemStatus.h"
#include "SetVehicleSize.h"
#include "SetExteriorLights.h"
#include "SetVehicleEventFlags.h"
#include "StartBsmRx.h"
#include "StopBsmRx.h"
#include "EnableGpsInput.h"
#include "SetLatitude.h"
#include "SetLongitude.h"
#include "SetElevation.h"
#include "SetPositionalAccuracy.h"
#include "SetSpeed.h"
#include "SetHeading.h"
#include "SetAccelerationSet4Way.h"
#include "SetGpsTime.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum D2945Request__value_PR {
	D2945Request__value_PR_NOTHING,	/* No components present */
	D2945Request__value_PR_SetInitialState,
	D2945Request__value_PR_StartBsmTx,
	D2945Request__value_PR_StopBsmTx,
	D2945Request__value_PR_EnableCongestionMitigation,
	D2945Request__value_PR_SetTemporaryID,
	D2945Request__value_PR_SetTransmissionState,
	D2945Request__value_PR_SetSteeringWheelAngle,
	D2945Request__value_PR_SetBrakeSystemStatus,
	D2945Request__value_PR_SetVehicleSize,
	D2945Request__value_PR_SetExteriorLights,
	D2945Request__value_PR_SetVehicleEventFlags,
	D2945Request__value_PR_StartBsmRx,
	D2945Request__value_PR_StopBsmRx,
	D2945Request__value_PR_EnableGpsInput,
	D2945Request__value_PR_SetLatitude,
	D2945Request__value_PR_SetLongitude,
	D2945Request__value_PR_SetElevation,
	D2945Request__value_PR_SetPositionalAccuracy,
	D2945Request__value_PR_SetSpeed,
	D2945Request__value_PR_SetHeading,
	D2945Request__value_PR_SetAccelerationSet4Way,
	D2945Request__value_PR_SetGpsTime
} D2945Request__value_PR;

/* D2945Request */
typedef struct D2945Request {
	MsgID_t	 messageId;
	struct D2945Request__value {
		D2945Request__value_PR present;
		union D2945Request__value_u {
			SetInitialState_t	 SetInitialState;
			StartBsmTx_t	 StartBsmTx;
			StopBsmTx_t	 StopBsmTx;
			EnableCongestionMitigation_t	 EnableCongestionMitigation;
			SetTemporaryID_t	 SetTemporaryID;
			SetTransmissionState_t	 SetTransmissionState;
			SetSteeringWheelAngle_t	 SetSteeringWheelAngle;
			SetBrakeSystemStatus_t	 SetBrakeSystemStatus;
			SetVehicleSize_t	 SetVehicleSize;
			SetExteriorLights_t	 SetExteriorLights;
			SetVehicleEventFlags_t	 SetVehicleEventFlags;
			StartBsmRx_t	 StartBsmRx;
			StopBsmRx_t	 StopBsmRx;
			EnableGpsInput_t	 EnableGpsInput;
			SetLatitude_t	 SetLatitude;
			SetLongitude_t	 SetLongitude;
			SetElevation_t	 SetElevation;
			SetPositionalAccuracy_t	 SetPositionalAccuracy;
			SetSpeed_t	 SetSpeed;
			SetHeading_t	 SetHeading;
			SetAccelerationSet4Way_t	 SetAccelerationSet4Way;
			SetGpsTime_t	 SetGpsTime;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} D2945Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_D2945Request;
extern asn_SEQUENCE_specifics_t asn_SPC_D2945Request_specs_1;
extern asn_TYPE_member_t asn_MBR_D2945Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _D2945Request_H_ */
#include <asn_internal.h>
