/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_DelUserService_H_
#define	_DelUserService_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Psid.h"
#include "RadioInterface.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DelUserService */
typedef struct DelUserService {
	Psid_t	 psid;
	RadioInterface_t	 radio;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DelUserService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DelUserService;
extern asn_SEQUENCE_specifics_t asn_SPC_DelUserService_specs_1;
extern asn_TYPE_member_t asn_MBR_DelUserService_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DelUserService_H_ */
#include <asn_internal.h>
