/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-80211"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Dot11Request_H_
#define	_Dot11Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "SetInitialState.h"
#include "Dot11SetWsmTxInfo.h"
#include "Dot11StartWsmTx.h"
#include "StopWsmTx.h"
#include "StartWsmRx.h"
#include "StopWsmRx.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Dot11Request__value_PR {
	Dot11Request__value_PR_NOTHING,	/* No components present */
	Dot11Request__value_PR_SetInitialState,
	Dot11Request__value_PR_Dot11SetWsmTxInfo,
	Dot11Request__value_PR_Dot11StartWsmTx,
	Dot11Request__value_PR_StopWsmTx,
	Dot11Request__value_PR_StartWsmRx,
	Dot11Request__value_PR_StopWsmRx
} Dot11Request__value_PR;

/* Dot11Request */
typedef struct Dot11Request {
	MsgID_t	 messageId;
	struct Dot11Request__value {
		Dot11Request__value_PR present;
		union Dot11Request__value_u {
			SetInitialState_t	 SetInitialState;
			Dot11SetWsmTxInfo_t	 Dot11SetWsmTxInfo;
			Dot11StartWsmTx_t	 Dot11StartWsmTx;
			StopWsmTx_t	 StopWsmTx;
			StartWsmRx_t	 StartWsmRx;
			StopWsmRx_t	 StopWsmRx;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Dot11Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Dot11Request;
extern asn_SEQUENCE_specifics_t asn_SPC_Dot11Request_specs_1;
extern asn_TYPE_member_t asn_MBR_Dot11Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Dot11Request_H_ */
#include <asn_internal.h>
