/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-80211"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Dot11SetWsmTxInfo_H_
#define	_Dot11SetWsmTxInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetWsmTxInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dot11SetWsmTxInfo */
typedef SetWsmTxInfo_t	 Dot11SetWsmTxInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Dot11SetWsmTxInfo;
asn_struct_free_f Dot11SetWsmTxInfo_free;
asn_struct_print_f Dot11SetWsmTxInfo_print;
asn_constr_check_f Dot11SetWsmTxInfo_constraint;
ber_type_decoder_f Dot11SetWsmTxInfo_decode_ber;
der_type_encoder_f Dot11SetWsmTxInfo_encode_der;
xer_type_decoder_f Dot11SetWsmTxInfo_decode_xer;
xer_type_encoder_f Dot11SetWsmTxInfo_encode_xer;
oer_type_decoder_f Dot11SetWsmTxInfo_decode_oer;
oer_type_encoder_f Dot11SetWsmTxInfo_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Dot11SetWsmTxInfo_H_ */
#include <asn_internal.h>
