/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-80211"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Dot11Indication_H_
#define	_Dot11Indication_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Indication.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dot11Indication */
typedef Indication_t	 Dot11Indication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Dot11Indication;
asn_struct_free_f Dot11Indication_free;
asn_struct_print_f Dot11Indication_print;
asn_constr_check_f Dot11Indication_constraint;
ber_type_decoder_f Dot11Indication_decode_ber;
der_type_encoder_f Dot11Indication_encode_der;
xer_type_decoder_f Dot11Indication_decode_xer;
xer_type_encoder_f Dot11Indication_encode_xer;
oer_type_decoder_f Dot11Indication_decode_oer;
oer_type_encoder_f Dot11Indication_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Dot11Indication_H_ */
#include <asn_internal.h>
