/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16093"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Dot3Request.h"

static const long asn_VAL_1_dot3SetInitialState = 1;
static const long asn_VAL_2_dot3SetWsmTxInfo = 2;
static const long asn_VAL_3_dot3StartWsmTx = 3;
static const long asn_VAL_4_dot3StopWsmTx = 4;
static const long asn_VAL_5_dot3StartWsaTxPerdiodic = 5;
static const long asn_VAL_6_dot3StopWsaTxPeriodic = 6;
static const long asn_VAL_7_dot3StartWsmRx = 7;
static const long asn_VAL_8_dot3StopWsmRx = 8;
static const long asn_VAL_9_dot3AddWsaProviderService = 9;
static const long asn_VAL_10_dot3ChangeWsaProviderService = 10;
static const long asn_VAL_11_dot3DelWsaProviderService = 11;
static const long asn_VAL_12_dot3AddUserService = 12;
static const long asn_VAL_13_dot3DelUserService = 13;
static const long asn_VAL_14_dot3GetIpv6InterfaceInfo = 14;
static const long asn_VAL_15_dot3SetIpv6Address = 15;
static const long asn_VAL_16_dot3StartIpv6Ping = 16;
static const long asn_VAL_17_dot3StopIpv6Ping = 17;
static const asn_ioc_cell_t asn_IOS_Dot3MessageTypes_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_1_dot3SetInitialState },
	{ "&Type", aioc__type, &asn_DEF_SetInitialState },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_2_dot3SetWsmTxInfo },
	{ "&Type", aioc__type, &asn_DEF_Dot3SetWsmTxInfo },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_3_dot3StartWsmTx },
	{ "&Type", aioc__type, &asn_DEF_Dot3StartWsmTx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_4_dot3StopWsmTx },
	{ "&Type", aioc__type, &asn_DEF_StopWsmTx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_5_dot3StartWsaTxPerdiodic },
	{ "&Type", aioc__type, &asn_DEF_StartWsaTxPerdiodic },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_6_dot3StopWsaTxPeriodic },
	{ "&Type", aioc__type, &asn_DEF_StopWsaTxPeriodic },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_7_dot3StartWsmRx },
	{ "&Type", aioc__type, &asn_DEF_StartWsmRx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_8_dot3StopWsmRx },
	{ "&Type", aioc__type, &asn_DEF_StopWsmRx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_9_dot3AddWsaProviderService },
	{ "&Type", aioc__type, &asn_DEF_AddWsaProviderService },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_10_dot3ChangeWsaProviderService },
	{ "&Type", aioc__type, &asn_DEF_ChangeWsaProviderService },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_11_dot3DelWsaProviderService },
	{ "&Type", aioc__type, &asn_DEF_DelWsaProviderService },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_12_dot3AddUserService },
	{ "&Type", aioc__type, &asn_DEF_AddUserService },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_13_dot3DelUserService },
	{ "&Type", aioc__type, &asn_DEF_DelUserService },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_14_dot3GetIpv6InterfaceInfo },
	{ "&Type", aioc__type, &asn_DEF_GetIPv6InterfaceInfo },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_15_dot3SetIpv6Address },
	{ "&Type", aioc__type, &asn_DEF_SetIPv6Address },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_16_dot3StartIpv6Ping },
	{ "&Type", aioc__type, &asn_DEF_StartIPv6Ping },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_17_dot3StopIpv6Ping },
	{ "&Type", aioc__type, &asn_DEF_StopIPv6Ping }
};
static const asn_ioc_set_t asn_IOS_Dot3MessageTypes_1[] = {
	17, 2, asn_IOS_Dot3MessageTypes_1_rows
};
static int
memb_messageId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_Dot3Request_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_Dot3MessageTypes_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Type */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct Dot3Request, messageId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_messageId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_value_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_TYPE_member_t asn_MBR_value_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.SetInitialState),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_SetInitialState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetInitialState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.Dot3SetWsmTxInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Dot3SetWsmTxInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Dot3SetWsmTxInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.Dot3StartWsmTx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Dot3StartWsmTx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Dot3StartWsmTx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StopWsmTx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopWsmTx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopWsmTx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StartWsaTxPerdiodic),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartWsaTxPerdiodic,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartWsaTxPerdiodic"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StopWsaTxPeriodic),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopWsaTxPeriodic,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopWsaTxPeriodic"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StartWsmRx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartWsmRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartWsmRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StopWsmRx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopWsmRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopWsmRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.AddWsaProviderService),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AddWsaProviderService,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AddWsaProviderService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.ChangeWsaProviderService),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ChangeWsaProviderService,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ChangeWsaProviderService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.DelWsaProviderService),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DelWsaProviderService,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DelWsaProviderService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.AddUserService),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AddUserService,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AddUserService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.DelUserService),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DelUserService,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DelUserService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.GetIPv6InterfaceInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GetIPv6InterfaceInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GetIPv6InterfaceInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.SetIPv6Address),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetIPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetIPv6Address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StartIPv6Ping),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartIPv6Ping,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartIPv6Ping"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request__value, choice.StopIPv6Ping),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopIPv6Ping,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopIPv6Ping"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 0 }, /* SetInitialState */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 15 }, /* Dot3SetWsmTxInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 14 }, /* Dot3StartWsmTx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -2, 13 }, /* StopWsmTx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -3, 12 }, /* StartWsaTxPerdiodic */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -4, 11 }, /* StopWsaTxPeriodic */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -5, 10 }, /* StartWsmRx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -6, 9 }, /* StopWsmRx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -7, 8 }, /* AddWsaProviderService */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -8, 7 }, /* ChangeWsaProviderService */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -9, 6 }, /* DelWsaProviderService */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -10, 5 }, /* AddUserService */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -11, 4 }, /* DelUserService */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -12, 3 }, /* GetIPv6InterfaceInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -13, 2 }, /* SetIPv6Address */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -14, 1 }, /* StartIPv6Ping */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -15, 0 } /* StopIPv6Ping */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_3 = {
	sizeof(struct Dot3Request__value),
	offsetof(struct Dot3Request__value, _asn_ctx),
	offsetof(struct Dot3Request__value, present),
	sizeof(((struct Dot3Request__value *)0)->present),
	asn_MAP_value_tag2el_3,
	17,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_3 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_3,
	17,	/* Elements count */
	&asn_SPC_value_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Dot3Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Dot3Request, messageId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgID,
		0,
		{ &asn_OER_memb_messageId_constr_2, 0,  memb_messageId_constraint_1 },
		0, 0, /* No default value */
		"messageId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct Dot3Request, value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_3,
		select_Dot3Request_value_type,
		{ &asn_OER_memb_value_constr_3, 0,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_Dot3Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Dot3Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* messageId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_Dot3Request_specs_1 = {
	sizeof(struct Dot3Request),
	offsetof(struct Dot3Request, _asn_ctx),
	asn_MAP_Dot3Request_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Dot3Request = {
	"Dot3Request",
	"Dot3Request",
	&asn_OP_SEQUENCE,
	asn_DEF_Dot3Request_tags_1,
	sizeof(asn_DEF_Dot3Request_tags_1)
		/sizeof(asn_DEF_Dot3Request_tags_1[0]), /* 1 */
	asn_DEF_Dot3Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_Dot3Request_tags_1)
		/sizeof(asn_DEF_Dot3Request_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Dot3Request_1,
	2,	/* Elements count */
	&asn_SPC_Dot3Request_specs_1	/* Additional specs */
};

