/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16093"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Dot3StartWsmTx_H_
#define	_Dot3StartWsmTx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StartWsmTx.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dot3StartWsmTx */
typedef StartWsmTx_t	 Dot3StartWsmTx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Dot3StartWsmTx;
asn_struct_free_f Dot3StartWsmTx_free;
asn_struct_print_f Dot3StartWsmTx_print;
asn_constr_check_f Dot3StartWsmTx_constraint;
ber_type_decoder_f Dot3StartWsmTx_decode_ber;
der_type_encoder_f Dot3StartWsmTx_encode_der;
xer_type_decoder_f Dot3StartWsmTx_decode_xer;
xer_type_encoder_f Dot3StartWsmTx_encode_xer;
oer_type_decoder_f Dot3StartWsmTx_decode_oer;
oer_type_encoder_f Dot3StartWsmTx_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Dot3StartWsmTx_H_ */
#include <asn_internal.h>
