/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16093"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Dot3Request_H_
#define	_Dot3Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "SetInitialState.h"
#include "Dot3SetWsmTxInfo.h"
#include "Dot3StartWsmTx.h"
#include "StopWsmTx.h"
#include "StartWsaTxPerdiodic.h"
#include "StopWsaTxPeriodic.h"
#include "StartWsmRx.h"
#include "StopWsmRx.h"
#include "AddWsaProviderService.h"
#include "ChangeWsaProviderService.h"
#include "DelWsaProviderService.h"
#include "AddUserService.h"
#include "DelUserService.h"
#include "GetIPv6InterfaceInfo.h"
#include "SetIPv6Address.h"
#include "StartIPv6Ping.h"
#include "StopIPv6Ping.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Dot3Request__value_PR {
	Dot3Request__value_PR_NOTHING,	/* No components present */
	Dot3Request__value_PR_SetInitialState,
	Dot3Request__value_PR_Dot3SetWsmTxInfo,
	Dot3Request__value_PR_Dot3StartWsmTx,
	Dot3Request__value_PR_StopWsmTx,
	Dot3Request__value_PR_StartWsaTxPerdiodic,
	Dot3Request__value_PR_StopWsaTxPeriodic,
	Dot3Request__value_PR_StartWsmRx,
	Dot3Request__value_PR_StopWsmRx,
	Dot3Request__value_PR_AddWsaProviderService,
	Dot3Request__value_PR_ChangeWsaProviderService,
	Dot3Request__value_PR_DelWsaProviderService,
	Dot3Request__value_PR_AddUserService,
	Dot3Request__value_PR_DelUserService,
	Dot3Request__value_PR_GetIPv6InterfaceInfo,
	Dot3Request__value_PR_SetIPv6Address,
	Dot3Request__value_PR_StartIPv6Ping,
	Dot3Request__value_PR_StopIPv6Ping
} Dot3Request__value_PR;

/* Dot3Request */
typedef struct Dot3Request {
	MsgID_t	 messageId;
	struct Dot3Request__value {
		Dot3Request__value_PR present;
		union Dot3Request__value_u {
			SetInitialState_t	 SetInitialState;
			Dot3SetWsmTxInfo_t	 Dot3SetWsmTxInfo;
			Dot3StartWsmTx_t	 Dot3StartWsmTx;
			StopWsmTx_t	 StopWsmTx;
			StartWsaTxPerdiodic_t	 StartWsaTxPerdiodic;
			StopWsaTxPeriodic_t	 StopWsaTxPeriodic;
			StartWsmRx_t	 StartWsmRx;
			StopWsmRx_t	 StopWsmRx;
			AddWsaProviderService_t	 AddWsaProviderService;
			ChangeWsaProviderService_t	 ChangeWsaProviderService;
			DelWsaProviderService_t	 DelWsaProviderService;
			AddUserService_t	 AddUserService;
			DelUserService_t	 DelUserService;
			GetIPv6InterfaceInfo_t	 GetIPv6InterfaceInfo;
			SetIPv6Address_t	 SetIPv6Address;
			StartIPv6Ping_t	 StartIPv6Ping;
			StopIPv6Ping_t	 StopIPv6Ping;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Dot3Request_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Dot3Request;
extern asn_SEQUENCE_specifics_t asn_SPC_Dot3Request_specs_1;
extern asn_TYPE_member_t asn_MBR_Dot3Request_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Dot3Request_H_ */
#include <asn_internal.h>
