/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16094"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Dot4StartWsmTx_H_
#define	_Dot4StartWsmTx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StartWsmTx.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dot4StartWsmTx */
typedef StartWsmTx_t	 Dot4StartWsmTx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Dot4StartWsmTx;
asn_struct_free_f Dot4StartWsmTx_free;
asn_struct_print_f Dot4StartWsmTx_print;
asn_constr_check_f Dot4StartWsmTx_constraint;
ber_type_decoder_f Dot4StartWsmTx_decode_ber;
der_type_encoder_f Dot4StartWsmTx_encode_der;
xer_type_decoder_f Dot4StartWsmTx_decode_xer;
xer_type_encoder_f Dot4StartWsmTx_encode_xer;
oer_type_decoder_f Dot4StartWsmTx_decode_oer;
oer_type_encoder_f Dot4StartWsmTx_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Dot4StartWsmTx_H_ */
#include <asn_internal.h>
