/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16094"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Dot4Request.h"

static const long asn_VAL_1_dot4SetInitialState = 1;
static const long asn_VAL_2_dot4SetWsmTxInfo = 2;
static const long asn_VAL_3_dot4StartWsmTx = 3;
static const long asn_VAL_4_dot4StopWsmTx = 4;
static const long asn_VAL_5_dot4StartWsmRx = 5;
static const long asn_VAL_6_dot4StopWsmRx = 6;
static const long asn_VAL_7_dot4GetIpv6InterfaceInfo = 7;
static const long asn_VAL_8_dot4SetIpv6Address = 8;
static const long asn_VAL_9_dot4StartIPv6Tx = 9;
static const long asn_VAL_10_dot4StopIPv6Tx = 10;
static const long asn_VAL_11_dot4StartIPv6Rx = 11;
static const long asn_VAL_12_dot4StopIPv6Rx = 12;
static const long asn_VAL_13_dot4StartIpv6Ping = 13;
static const long asn_VAL_14_dot4StopIpv6Ping = 14;
static const long asn_VAL_15_dot4AddTxProfile = 15;
static const long asn_VAL_16_dot4DelTxProfile = 16;
static const asn_ioc_cell_t asn_IOS_Dot4MessageTypes_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_1_dot4SetInitialState },
	{ "&Type", aioc__type, &asn_DEF_SetInitialState },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_2_dot4SetWsmTxInfo },
	{ "&Type", aioc__type, &asn_DEF_Dot4SetWsmTxInfo },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_3_dot4StartWsmTx },
	{ "&Type", aioc__type, &asn_DEF_Dot4StartWsmTx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_4_dot4StopWsmTx },
	{ "&Type", aioc__type, &asn_DEF_StopWsmTx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_5_dot4StartWsmRx },
	{ "&Type", aioc__type, &asn_DEF_StartWsmRx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_6_dot4StopWsmRx },
	{ "&Type", aioc__type, &asn_DEF_StopWsmRx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_7_dot4GetIpv6InterfaceInfo },
	{ "&Type", aioc__type, &asn_DEF_GetIPv6InterfaceInfo },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_8_dot4SetIpv6Address },
	{ "&Type", aioc__type, &asn_DEF_SetIPv6Address },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_9_dot4StartIPv6Tx },
	{ "&Type", aioc__type, &asn_DEF_StartIPv6Tx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_10_dot4StopIPv6Tx },
	{ "&Type", aioc__type, &asn_DEF_StopIPv6Tx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_11_dot4StartIPv6Rx },
	{ "&Type", aioc__type, &asn_DEF_StartIPv6Rx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_12_dot4StopIPv6Rx },
	{ "&Type", aioc__type, &asn_DEF_StopIPv6Rx },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_13_dot4StartIpv6Ping },
	{ "&Type", aioc__type, &asn_DEF_StartIPv6Ping },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_14_dot4StopIpv6Ping },
	{ "&Type", aioc__type, &asn_DEF_StopIPv6Ping },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_15_dot4AddTxProfile },
	{ "&Type", aioc__type, &asn_DEF_AddTxProfile },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_16_dot4DelTxProfile },
	{ "&Type", aioc__type, &asn_DEF_DelTxProfile }
};
static const asn_ioc_set_t asn_IOS_Dot4MessageTypes_1[] = {
	16, 2, asn_IOS_Dot4MessageTypes_1_rows
};
static int
memb_messageId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_Dot4Request_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_Dot4MessageTypes_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Type */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct Dot4Request, messageId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_messageId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_value_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_TYPE_member_t asn_MBR_value_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.SetInitialState),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_SetInitialState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetInitialState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.Dot4SetWsmTxInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Dot4SetWsmTxInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Dot4SetWsmTxInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.Dot4StartWsmTx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Dot4StartWsmTx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Dot4StartWsmTx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StopWsmTx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopWsmTx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopWsmTx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StartWsmRx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartWsmRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartWsmRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StopWsmRx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopWsmRx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopWsmRx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.GetIPv6InterfaceInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GetIPv6InterfaceInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GetIPv6InterfaceInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.SetIPv6Address),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetIPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetIPv6Address"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StartIPv6Tx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartIPv6Tx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartIPv6Tx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StopIPv6Tx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopIPv6Tx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopIPv6Tx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StartIPv6Rx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartIPv6Rx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartIPv6Rx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StopIPv6Rx),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopIPv6Rx,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopIPv6Rx"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StartIPv6Ping),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StartIPv6Ping,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StartIPv6Ping"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.StopIPv6Ping),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_StopIPv6Ping,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"StopIPv6Ping"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.AddTxProfile),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AddTxProfile,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AddTxProfile"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request__value, choice.DelTxProfile),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DelTxProfile,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DelTxProfile"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 0 }, /* SetInitialState */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 14 }, /* Dot4SetWsmTxInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 13 }, /* Dot4StartWsmTx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -2, 12 }, /* StopWsmTx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -3, 11 }, /* StartWsmRx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -4, 10 }, /* StopWsmRx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -5, 9 }, /* GetIPv6InterfaceInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -6, 8 }, /* SetIPv6Address */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -7, 7 }, /* StartIPv6Tx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -8, 6 }, /* StopIPv6Tx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -9, 5 }, /* StartIPv6Rx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -10, 4 }, /* StopIPv6Rx */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -11, 3 }, /* StartIPv6Ping */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -12, 2 }, /* StopIPv6Ping */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -13, 1 }, /* AddTxProfile */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -14, 0 } /* DelTxProfile */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_3 = {
	sizeof(struct Dot4Request__value),
	offsetof(struct Dot4Request__value, _asn_ctx),
	offsetof(struct Dot4Request__value, present),
	sizeof(((struct Dot4Request__value *)0)->present),
	asn_MAP_value_tag2el_3,
	16,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_3 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_3,
	16,	/* Elements count */
	&asn_SPC_value_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Dot4Request_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Dot4Request, messageId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgID,
		0,
		{ &asn_OER_memb_messageId_constr_2, 0,  memb_messageId_constraint_1 },
		0, 0, /* No default value */
		"messageId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct Dot4Request, value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_3,
		select_Dot4Request_value_type,
		{ &asn_OER_memb_value_constr_3, 0,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_Dot4Request_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Dot4Request_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* messageId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_Dot4Request_specs_1 = {
	sizeof(struct Dot4Request),
	offsetof(struct Dot4Request, _asn_ctx),
	asn_MAP_Dot4Request_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Dot4Request = {
	"Dot4Request",
	"Dot4Request",
	&asn_OP_SEQUENCE,
	asn_DEF_Dot4Request_tags_1,
	sizeof(asn_DEF_Dot4Request_tags_1)
		/sizeof(asn_DEF_Dot4Request_tags_1[0]), /* 1 */
	asn_DEF_Dot4Request_tags_1,	/* Same as above */
	sizeof(asn_DEF_Dot4Request_tags_1)
		/sizeof(asn_DEF_Dot4Request_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Dot4Request_1,
	2,	/* Elements count */
	&asn_SPC_Dot4Request_specs_1	/* Additional specs */
};

