/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_DummyExtension_H_
#define	_DummyExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DummyExtension */
typedef NULL_t	 DummyExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DummyExtension;
asn_struct_free_f DummyExtension_free;
asn_struct_print_f DummyExtension_print;
asn_constr_check_f DummyExtension_constraint;
ber_type_decoder_f DummyExtension_decode_ber;
der_type_encoder_f DummyExtension_encode_der;
xer_type_decoder_f DummyExtension_decode_xer;
xer_type_encoder_f DummyExtension_encode_xer;
oer_type_decoder_f DummyExtension_decode_oer;
oer_type_encoder_f DummyExtension_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _DummyExtension_H_ */
#include <asn_internal.h>
