/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "EdcaParameterSet.h"

asn_TYPE_member_t asn_MBR_EdcaParameterSet_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterSet, acbeRecord),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EdcaParameterRecord,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acbeRecord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterSet, acbkRecord),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EdcaParameterRecord,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acbkRecord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterSet, acviRecord),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EdcaParameterRecord,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acviRecord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterSet, acvoRecord),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EdcaParameterRecord,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"acvoRecord"
		},
};
static const ber_tlv_tag_t asn_DEF_EdcaParameterSet_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EdcaParameterSet_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* acbeRecord */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* acbkRecord */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* acviRecord */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* acvoRecord */
};
asn_SEQUENCE_specifics_t asn_SPC_EdcaParameterSet_specs_1 = {
	sizeof(struct EdcaParameterSet),
	offsetof(struct EdcaParameterSet, _asn_ctx),
	asn_MAP_EdcaParameterSet_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EdcaParameterSet = {
	"EdcaParameterSet",
	"EdcaParameterSet",
	&asn_OP_SEQUENCE,
	asn_DEF_EdcaParameterSet_tags_1,
	sizeof(asn_DEF_EdcaParameterSet_tags_1)
		/sizeof(asn_DEF_EdcaParameterSet_tags_1[0]), /* 1 */
	asn_DEF_EdcaParameterSet_tags_1,	/* Same as above */
	sizeof(asn_DEF_EdcaParameterSet_tags_1)
		/sizeof(asn_DEF_EdcaParameterSet_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EdcaParameterSet_1,
	4,	/* Elements count */
	&asn_SPC_EdcaParameterSet_specs_1	/* Additional specs */
};

