/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "EdcaParameterRecord.h"

static int
memb_res_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_aci_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_acm_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_aifsn_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ecwMax_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ecwMin_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_txopLimit_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_res_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_aci_constr_3 CC_NOTUSED = {
	{ 1, 1 }	/* (0..3) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_acm_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..1) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_aifsn_constr_5 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_ecwMax_constr_6 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_ecwMin_constr_7 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_txopLimit_constr_8 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
asn_TYPE_member_t asn_MBR_EdcaParameterRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, res),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_res_constr_2, 0,  memb_res_constraint_1 },
		0, 0, /* No default value */
		"res"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, aci),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_aci_constr_3, 0,  memb_aci_constraint_1 },
		0, 0, /* No default value */
		"aci"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, acm),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_acm_constr_4, 0,  memb_acm_constraint_1 },
		0, 0, /* No default value */
		"acm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, aifsn),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_aifsn_constr_5, 0,  memb_aifsn_constraint_1 },
		0, 0, /* No default value */
		"aifsn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, ecwMax),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ecwMax_constr_6, 0,  memb_ecwMax_constraint_1 },
		0, 0, /* No default value */
		"ecwMax"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, ecwMin),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_ecwMin_constr_7, 0,  memb_ecwMin_constraint_1 },
		0, 0, /* No default value */
		"ecwMin"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EdcaParameterRecord, txopLimit),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_txopLimit_constr_8, 0,  memb_txopLimit_constraint_1 },
		0, 0, /* No default value */
		"txopLimit"
		},
};
static const ber_tlv_tag_t asn_DEF_EdcaParameterRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EdcaParameterRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* res */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* aci */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* acm */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aifsn */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ecwMax */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ecwMin */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* txopLimit */
};
asn_SEQUENCE_specifics_t asn_SPC_EdcaParameterRecord_specs_1 = {
	sizeof(struct EdcaParameterRecord),
	offsetof(struct EdcaParameterRecord, _asn_ctx),
	asn_MAP_EdcaParameterRecord_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EdcaParameterRecord = {
	"EdcaParameterRecord",
	"EdcaParameterRecord",
	&asn_OP_SEQUENCE,
	asn_DEF_EdcaParameterRecord_tags_1,
	sizeof(asn_DEF_EdcaParameterRecord_tags_1)
		/sizeof(asn_DEF_EdcaParameterRecord_tags_1[0]), /* 1 */
	asn_DEF_EdcaParameterRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_EdcaParameterRecord_tags_1)
		/sizeof(asn_DEF_EdcaParameterRecord_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EdcaParameterRecord_1,
	7,	/* Elements count */
	&asn_SPC_EdcaParameterRecord_specs_1	/* Additional specs */
};

