/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_EdcaParameterSet_H_
#define	_EdcaParameterSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EdcaParameterRecord.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EdcaParameterSet */
typedef struct EdcaParameterSet {
	EdcaParameterRecord_t	 acbeRecord;
	EdcaParameterRecord_t	 acbkRecord;
	EdcaParameterRecord_t	 acviRecord;
	EdcaParameterRecord_t	 acvoRecord;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EdcaParameterSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EdcaParameterSet;
extern asn_SEQUENCE_specifics_t asn_SPC_EdcaParameterSet_specs_1;
extern asn_TYPE_member_t asn_MBR_EdcaParameterSet_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _EdcaParameterSet_H_ */
#include <asn_internal.h>
