/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_EdcaParameterRecord_H_
#define	_EdcaParameterRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EdcaParameterRecord */
typedef struct EdcaParameterRecord {
	long	 res;
	long	 aci;
	long	 acm;
	long	 aifsn;
	long	 ecwMax;
	long	 ecwMin;
	long	 txopLimit;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EdcaParameterRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EdcaParameterRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_EdcaParameterRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_EdcaParameterRecord_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _EdcaParameterRecord_H_ */
#include <asn_internal.h>
