/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_EnableGpsInput_H_
#define	_EnableGpsInput_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EnableGpsInput */
typedef BOOLEAN_t	 EnableGpsInput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnableGpsInput;
asn_struct_free_f EnableGpsInput_free;
asn_struct_print_f EnableGpsInput_print;
asn_constr_check_f EnableGpsInput_constraint;
ber_type_decoder_f EnableGpsInput_decode_ber;
der_type_encoder_f EnableGpsInput_encode_der;
xer_type_decoder_f EnableGpsInput_decode_xer;
xer_type_encoder_f EnableGpsInput_encode_xer;
oer_type_decoder_f EnableGpsInput_decode_oer;
oer_type_encoder_f EnableGpsInput_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _EnableGpsInput_H_ */
#include <asn_internal.h>
