/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-eventHandling"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "EventParamsChoice.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_EventParamsChoice_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_EventParamsChoice_value2enum_1[] = {
	{ 0,	7,	"service" },
	{ 1,	3,	"wsm" },
	{ 2,	2,	"ip" },
	{ 3,	11,	"d80211frame" },
	{ 4,	8,	"security" }
};
static const unsigned int asn_MAP_EventParamsChoice_enum2value_1[] = {
	3,	/* d80211frame(3) */
	2,	/* ip(2) */
	4,	/* security(4) */
	0,	/* service(0) */
	1	/* wsm(1) */
};
const asn_INTEGER_specifics_t asn_SPC_EventParamsChoice_specs_1 = {
	asn_MAP_EventParamsChoice_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_EventParamsChoice_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_EventParamsChoice_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EventParamsChoice = {
	"EventParamsChoice",
	"EventParamsChoice",
	&asn_OP_ENUMERATED,
	asn_DEF_EventParamsChoice_tags_1,
	sizeof(asn_DEF_EventParamsChoice_tags_1)
		/sizeof(asn_DEF_EventParamsChoice_tags_1[0]), /* 1 */
	asn_DEF_EventParamsChoice_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventParamsChoice_tags_1)
		/sizeof(asn_DEF_EventParamsChoice_tags_1[0]), /* 1 */
	{ &asn_OER_type_EventParamsChoice_constr_1, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_EventParamsChoice_specs_1	/* Additional specs */
};

