/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Event_H_
#define	_Event_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Event {
	Event_reserved	= 0,
	Event_e80211PktRx	= 1,
	Event_e16093PktRx	= 2,
	Event_eWsmPktRx	= 3,
	Event_eIpv6PktRx	= 4,
	Event_eIcmp6PktRx	= 5,
	Event_eIpv6ConfigChanged	= 6,
	Event_eDot3ChannelAssigned	= 7,
	Event_eDot3RequestMatchedAvailAppService	= 8,
	Event_eDot2VerificationCompleteWithResult	= 9,
	Event_dummy10	= 10,
	Event_dummy11	= 11,
	Event_dummy12	= 12,
	Event_dummy13	= 13,
	Event_dummy14	= 14,
	Event_exception	= 15
} e_Event;

/* Event */
typedef ENUMERATED_t	 Event_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Event;
extern const asn_INTEGER_specifics_t asn_SPC_Event_specs_1;
asn_struct_free_f Event_free;
asn_struct_print_f Event_print;
asn_constr_check_f Event_constraint;
ber_type_decoder_f Event_decode_ber;
der_type_encoder_f Event_encode_der;
xer_type_decoder_f Event_decode_xer;
xer_type_encoder_f Event_encode_xer;
oer_type_decoder_f Event_decode_oer;
oer_type_encoder_f Event_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Event_H_ */
#include <asn_internal.h>
