/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_EventParams_H_
#define	_EventParams_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceParameters.h"
#include "WsmParameters.h"
#include "IpParameters.h"
#include "D80211Parameters.h"
#include "SecResultParams.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EventParams_PR {
	EventParams_PR_NOTHING,	/* No components present */
	EventParams_PR_service,
	EventParams_PR_wsm,
	EventParams_PR_ip,
	EventParams_PR_d80211frame,
	EventParams_PR_security
	/* Extensions may appear below */
	
} EventParams_PR;

/* EventParams */
typedef struct EventParams {
	EventParams_PR present;
	union EventParams_u {
		ServiceParameters_t	 service;
		WsmParameters_t	 wsm;
		IpParameters_t	 ip;
		D80211Parameters_t	 d80211frame;
		SecResultParams_t	 security;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventParams_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventParams;
extern asn_CHOICE_specifics_t asn_SPC_EventParams_specs_1;
extern asn_TYPE_member_t asn_MBR_EventParams_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _EventParams_H_ */
#include <asn_internal.h>
