/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "ExceptionId.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_ExceptionId_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_ExceptionId_value2enum_1[] = {
	{ 0,	8,	"reserved" },
	{ 1,	14,	"critical-error" },
	{ 2,	25,	"incorrect-parameter-value" },
	{ 3,	17,	"missing-parameter" },
	{ 4,	27,	"radio-interface-unavailable" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ExceptionId_enum2value_1[] = {
	1,	/* critical-error(1) */
	2,	/* incorrect-parameter-value(2) */
	3,	/* missing-parameter(3) */
	4,	/* radio-interface-unavailable(4) */
	0	/* reserved(0) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_ExceptionId_specs_1 = {
	asn_MAP_ExceptionId_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_ExceptionId_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	6,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ExceptionId_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ExceptionId = {
	"ExceptionId",
	"ExceptionId",
	&asn_OP_ENUMERATED,
	asn_DEF_ExceptionId_tags_1,
	sizeof(asn_DEF_ExceptionId_tags_1)
		/sizeof(asn_DEF_ExceptionId_tags_1[0]), /* 1 */
	asn_DEF_ExceptionId_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExceptionId_tags_1)
		/sizeof(asn_DEF_ExceptionId_tags_1[0]), /* 1 */
	{ &asn_OER_type_ExceptionId_constr_1, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ExceptionId_specs_1	/* Additional specs */
};

