/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Exception_H_
#define	_Exception_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExceptionType.h"
#include "ExceptionId.h"
#include "Module.h"
#include "ExceptionText.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Exception */
typedef struct Exception {
	ExceptionType_t	 type;
	ExceptionId_t	*id	/* OPTIONAL */;
	Module_t	*module	/* OPTIONAL */;
	ExceptionText_t	*description	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Exception_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Exception;
extern asn_SEQUENCE_specifics_t asn_SPC_Exception_specs_1;
extern asn_TYPE_member_t asn_MBR_Exception_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _Exception_H_ */
#include <asn_internal.h>
