/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ExceptionType_H_
#define	_ExceptionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExceptionType {
	ExceptionType_info	= 0,
	ExceptionType_warning	= 1,
	ExceptionType_error	= 2
} e_ExceptionType;

/* ExceptionType */
typedef ENUMERATED_t	 ExceptionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExceptionType;
extern const asn_INTEGER_specifics_t asn_SPC_ExceptionType_specs_1;
asn_struct_free_f ExceptionType_free;
asn_struct_print_f ExceptionType_print;
asn_constr_check_f ExceptionType_constraint;
ber_type_decoder_f ExceptionType_decode_ber;
der_type_encoder_f ExceptionType_encode_der;
xer_type_decoder_f ExceptionType_decode_xer;
xer_type_encoder_f ExceptionType_encode_xer;
oer_type_decoder_f ExceptionType_decode_oer;
oer_type_encoder_f ExceptionType_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExceptionType_H_ */
#include <asn_internal.h>
