/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ExceptionText_H_
#define	_ExceptionText_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExceptionText */
typedef UTF8String_t	 ExceptionText_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExceptionText;
asn_struct_free_f ExceptionText_free;
asn_struct_print_f ExceptionText_print;
asn_constr_check_f ExceptionText_constraint;
ber_type_decoder_f ExceptionText_decode_ber;
der_type_encoder_f ExceptionText_encode_der;
xer_type_decoder_f ExceptionText_decode_xer;
xer_type_encoder_f ExceptionText_encode_xer;
oer_type_decoder_f ExceptionText_decode_oer;
oer_type_encoder_f ExceptionText_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExceptionText_H_ */
#include <asn_internal.h>
