/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Exception.h"

asn_TYPE_member_t asn_MBR_Exception_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Exception, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExceptionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"type"
		},
	{ ATF_POINTER, 3, offsetof(struct Exception, id),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExceptionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_POINTER, 2, offsetof(struct Exception, module),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Module,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"module"
		},
	{ ATF_POINTER, 1, offsetof(struct Exception, description),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExceptionText,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"description"
		},
};
static const int asn_MAP_Exception_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_Exception_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Exception_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* module */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* description */
};
asn_SEQUENCE_specifics_t asn_SPC_Exception_specs_1 = {
	sizeof(struct Exception),
	offsetof(struct Exception, _asn_ctx),
	asn_MAP_Exception_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Exception_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Exception = {
	"Exception",
	"Exception",
	&asn_OP_SEQUENCE,
	asn_DEF_Exception_tags_1,
	sizeof(asn_DEF_Exception_tags_1)
		/sizeof(asn_DEF_Exception_tags_1[0]), /* 1 */
	asn_DEF_Exception_tags_1,	/* Same as above */
	sizeof(asn_DEF_Exception_tags_1)
		/sizeof(asn_DEF_Exception_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Exception_1,
	4,	/* Elements count */
	&asn_SPC_Exception_specs_1	/* Additional specs */
};

