/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Extension.h"

static const long asn_VAL_1_c_RepeatRate = 17;
static const long asn_VAL_2_c_2Dlocation = 5;
static const long asn_VAL_3_c_3Dlocation = 6;
static const long asn_VAL_4_c_advertiserID = 7;
static const asn_ioc_cell_t asn_IOS_SrvAdvMsgHeaderExtTypes_1_rows[] = {
	{ "&extRef", aioc__value, &asn_DEF_RefExt, &asn_VAL_1_c_RepeatRate },
	{ "&ExtValue", aioc__type, &asn_DEF_WsaRepeatRate },
	{ "&extRef", aioc__value, &asn_DEF_RefExt, &asn_VAL_2_c_2Dlocation },
	{ "&ExtValue", aioc__type, &asn_DEF_TwoDLocation },
	{ "&extRef", aioc__value, &asn_DEF_RefExt, &asn_VAL_3_c_3Dlocation },
	{ "&ExtValue", aioc__type, &asn_DEF_ThreeDLocation },
	{ "&extRef", aioc__value, &asn_DEF_RefExt, &asn_VAL_4_c_advertiserID },
	{ "&ExtValue", aioc__type, &asn_DEF_AdvertiserIdentifier }
};
static const asn_ioc_set_t asn_IOS_SrvAdvMsgHeaderExtTypes_1[] = {
	4, 2, asn_IOS_SrvAdvMsgHeaderExtTypes_1_rows
};
static int
memb_extensionId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_Extension_73P0_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SrvAdvMsgHeaderExtTypes_1;
	size_t constraining_column = 0; /* &extRef */
	size_t for_column = 1; /* &ExtValue */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct Extension_73P0, extensionId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_extensionId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_value_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_TYPE_member_t asn_MBR_value_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Extension_73P0__value, choice.WsaRepeatRate),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_WsaRepeatRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"WsaRepeatRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Extension_73P0__value, choice.TwoDLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_TwoDLocation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"TwoDLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Extension_73P0__value, choice.ThreeDLocation),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ThreeDLocation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ThreeDLocation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Extension_73P0__value, choice.AdvertiserIdentifier),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_AdvertiserIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"AdvertiserIdentifier"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* WsaRepeatRate */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 3, 0, 0 }, /* AdvertiserIdentifier */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* TwoDLocation */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 0 } /* ThreeDLocation */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_3 = {
	sizeof(struct Extension_73P0__value),
	offsetof(struct Extension_73P0__value, _asn_ctx),
	offsetof(struct Extension_73P0__value, present),
	sizeof(((struct Extension_73P0__value *)0)->present),
	asn_MAP_value_tag2el_3,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_3 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_3,
	4,	/* Elements count */
	&asn_SPC_value_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Extension_73P0_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Extension_73P0, extensionId),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_RefExt,
		0,
		{ &asn_OER_memb_extensionId_constr_2, 0,  memb_extensionId_constraint_1 },
		0, 0, /* No default value */
		"extensionId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct Extension_73P0, value),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_value_3,
		select_Extension_73P0_value_type,
		{ &asn_OER_memb_value_constr_3, 0,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_Extension_73P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Extension_73P0_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 } /* extensionId */
};
asn_SEQUENCE_specifics_t asn_SPC_Extension_73P0_specs_1 = {
	sizeof(struct Extension_73P0),
	offsetof(struct Extension_73P0, _asn_ctx),
	asn_MAP_Extension_73P0_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Extension_73P0 = {
	"Extension",
	"Extension",
	&asn_OP_SEQUENCE,
	asn_DEF_Extension_73P0_tags_1,
	sizeof(asn_DEF_Extension_73P0_tags_1)
		/sizeof(asn_DEF_Extension_73P0_tags_1[0]), /* 1 */
	asn_DEF_Extension_73P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_Extension_73P0_tags_1)
		/sizeof(asn_DEF_Extension_73P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Extension_73P0_1,
	2,	/* Elements count */
	&asn_SPC_Extension_73P0_specs_1	/* Additional specs */
};

