/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Extension_H_
#define	_Extension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RefExt.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "WsaRepeatRate.h"
#include "TwoDLocation.h"
#include "ThreeDLocation.h"
#include "AdvertiserIdentifier.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Extension_73P0__value_PR {
	Extension_73P0__value_PR_NOTHING,	/* No components present */
	Extension_73P0__value_PR_WsaRepeatRate,
	Extension_73P0__value_PR_TwoDLocation,
	Extension_73P0__value_PR_ThreeDLocation,
	Extension_73P0__value_PR_AdvertiserIdentifier
} Extension_73P0__value_PR;

/* Extension */
typedef struct Extension_73P0 {
	RefExt_t	 extensionId;
	struct Extension_73P0__value {
		Extension_73P0__value_PR present;
		union Extension_73P0__value_u {
			WsaRepeatRate_t	 WsaRepeatRate;
			TwoDLocation_t	 TwoDLocation;
			ThreeDLocation_t	 ThreeDLocation;
			AdvertiserIdentifier_t	 AdvertiserIdentifier;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Extension_73P0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Extension_73P0;
extern asn_SEQUENCE_specifics_t asn_SPC_Extension_73P0_specs_1;
extern asn_TYPE_member_t asn_MBR_Extension_73P0_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Extension_H_ */
#include <asn_internal.h>
