/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-Dispatcher"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Frame.h"

static asn_oer_constraints_t asn_OER_type_Frame_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_Frame_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Frame, choice.d16093),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TCI16093,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"d16093"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Frame, choice.d80211),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TCI80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"d80211"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Frame, choice.d16094),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TCI16094,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"d16094"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Frame, choice.d29451),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TCI29451,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"d29451"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Frame, choice.sutCtrl),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_TCISutControl,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sutCtrl"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Frame_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* d16093 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* d80211 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 }, /* d16094 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 3, 0, 0 }, /* d29451 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 4, 0, 0 } /* sutCtrl */
};
asn_CHOICE_specifics_t asn_SPC_Frame_specs_1 = {
	sizeof(struct Frame),
	offsetof(struct Frame, _asn_ctx),
	offsetof(struct Frame, present),
	sizeof(((struct Frame *)0)->present),
	asn_MAP_Frame_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Frame = {
	"Frame",
	"Frame",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_Frame_constr_1, 0, CHOICE_constraint },
	asn_MBR_Frame_1,
	5,	/* Elements count */
	&asn_SPC_Frame_specs_1	/* Additional specs */
};

