/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_GatewayMacAddress_H_
#define	_GatewayMacAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MACaddress.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GatewayMacAddress */
typedef MACaddress_t	 GatewayMacAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GatewayMacAddress;
asn_struct_free_f GatewayMacAddress_free;
asn_struct_print_f GatewayMacAddress_print;
asn_constr_check_f GatewayMacAddress_constraint;
ber_type_decoder_f GatewayMacAddress_decode_ber;
der_type_encoder_f GatewayMacAddress_encode_der;
xer_type_decoder_f GatewayMacAddress_decode_xer;
xer_type_encoder_f GatewayMacAddress_encode_xer;
oer_type_decoder_f GatewayMacAddress_decode_oer;
oer_type_encoder_f GatewayMacAddress_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _GatewayMacAddress_H_ */
#include <asn_internal.h>
