/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_GetIPv6InterfaceInfo_H_
#define	_GetIPv6InterfaceInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetIPv6InterfaceInfo */
typedef struct GetIPv6InterfaceInfo {
	RadioInterface_t	 radio;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetIPv6InterfaceInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetIPv6InterfaceInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_GetIPv6InterfaceInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_GetIPv6InterfaceInfo_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _GetIPv6InterfaceInfo_H_ */
#include <asn_internal.h>
