/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Indication.h"

static int
memb_radio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_radio_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_Indication_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Indication, radio),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ &asn_OER_memb_radio_constr_2, 0,  memb_radio_constraint_1 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Indication, event),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Event,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"event"
		},
	{ ATF_POINTER, 3, offsetof(struct Indication, eventParams),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_EventParams,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventParams"
		},
	{ ATF_POINTER, 2, offsetof(struct Indication, pdu),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Pdu,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pdu"
		},
	{ ATF_POINTER, 1, offsetof(struct Indication, exception),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Exception,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exception"
		},
};
static const int asn_MAP_Indication_oms_1[] = { 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_Indication_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Indication_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* event */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eventParams */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* pdu */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* exception */
};
asn_SEQUENCE_specifics_t asn_SPC_Indication_specs_1 = {
	sizeof(struct Indication),
	offsetof(struct Indication, _asn_ctx),
	asn_MAP_Indication_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_Indication_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Indication = {
	"Indication",
	"Indication",
	&asn_OP_SEQUENCE,
	asn_DEF_Indication_tags_1,
	sizeof(asn_DEF_Indication_tags_1)
		/sizeof(asn_DEF_Indication_tags_1[0]), /* 1 */
	asn_DEF_Indication_tags_1,	/* Same as above */
	sizeof(asn_DEF_Indication_tags_1)
		/sizeof(asn_DEF_Indication_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Indication_1,
	5,	/* Elements count */
	&asn_SPC_Indication_specs_1	/* Additional specs */
};

