/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Indication_H_
#define	_Indication_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include "Event.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EventParams;
struct Pdu;
struct Exception;

/* Indication */
typedef struct Indication {
	RadioInterface_t	 radio;
	Event_t	 event;
	struct EventParams	*eventParams	/* OPTIONAL */;
	struct Pdu	*pdu	/* OPTIONAL */;
	struct Exception	*exception	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Indication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Indication;
extern asn_SEQUENCE_specifics_t asn_SPC_Indication_specs_1;
extern asn_TYPE_member_t asn_MBR_Indication_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EventParams.h"
#include "Pdu.h"
#include "Exception.h"

#endif	/* _Indication_H_ */
#include <asn_internal.h>
