/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "IpParameters.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static int
memb_interfaceName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 1 && size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_protocol_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_memb_interfaceName_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static const asn_INTEGER_enum_map_t asn_MAP_protocol_value2enum_4[] = {
	{ 0,	3,	"tcp" },
	{ 1,	3,	"udp" },
	{ 2,	6,	"icmpv6" }
};
static const unsigned int asn_MAP_protocol_enum2value_4[] = {
	2,	/* icmpv6(2) */
	0,	/* tcp(0) */
	1	/* udp(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_protocol_specs_4 = {
	asn_MAP_protocol_value2enum_4,	/* "tag" => N; sorted by tag */
	asn_MAP_protocol_enum2value_4,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_protocol_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_protocol_4 = {
	"protocol",
	"protocol",
	&asn_OP_ENUMERATED,
	asn_DEF_protocol_tags_4,
	sizeof(asn_DEF_protocol_tags_4)
		/sizeof(asn_DEF_protocol_tags_4[0]) - 1, /* 1 */
	asn_DEF_protocol_tags_4,	/* Same as above */
	sizeof(asn_DEF_protocol_tags_4)
		/sizeof(asn_DEF_protocol_tags_4[0]), /* 2 */
	{ &asn_OER_type_protocol_constr_4, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_protocol_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_IpParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpParameters, interfaceName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_interfaceName_constr_2, 0,  memb_interfaceName_constraint_1 },
		0, 0, /* No default value */
		"interfaceName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpParameters, sourceIPaddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sourceIPaddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpParameters, protocol),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_protocol_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocol"
		},
};
static const ber_tlv_tag_t asn_DEF_IpParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interfaceName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sourceIPaddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* protocol */
};
asn_SEQUENCE_specifics_t asn_SPC_IpParameters_specs_1 = {
	sizeof(struct IpParameters),
	offsetof(struct IpParameters, _asn_ctx),
	asn_MAP_IpParameters_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IpParameters = {
	"IpParameters",
	"IpParameters",
	&asn_OP_SEQUENCE,
	asn_DEF_IpParameters_tags_1,
	sizeof(asn_DEF_IpParameters_tags_1)
		/sizeof(asn_DEF_IpParameters_tags_1[0]), /* 1 */
	asn_DEF_IpParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpParameters_tags_1)
		/sizeof(asn_DEF_IpParameters_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IpParameters_1,
	3,	/* Elements count */
	&asn_SPC_IpParameters_specs_1	/* Additional specs */
};

