/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-responseInfo"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Ipv6InterfaceInfo.h"

static int
memb_interfaceName_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 1 && size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_interfaceName_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_TYPE_member_t asn_MBR_ipAddress_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ipAddress_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ipAddress_specs_4 = {
	sizeof(struct Ipv6InterfaceInfo__Member__ipAddress),
	offsetof(struct Ipv6InterfaceInfo__Member__ipAddress, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ipAddress_4 = {
	"ipAddress",
	"ipAddress",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ipAddress_tags_4,
	sizeof(asn_DEF_ipAddress_tags_4)
		/sizeof(asn_DEF_ipAddress_tags_4[0]) - 1, /* 1 */
	asn_DEF_ipAddress_tags_4,	/* Same as above */
	sizeof(asn_DEF_ipAddress_tags_4)
		/sizeof(asn_DEF_ipAddress_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_ipAddress_4,
	1,	/* Single element */
	&asn_SPC_ipAddress_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ipv6InterfaceInfo__Member, interfaceName),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_interfaceName_constr_3, 0,  memb_interfaceName_constraint_2 },
		0, 0, /* No default value */
		"interfaceName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ipv6InterfaceInfo__Member, ipAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ipAddress_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ipv6InterfaceInfo__Member, macAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MACaddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"macAddress"
		},
	{ ATF_POINTER, 3, offsetof(struct Ipv6InterfaceInfo__Member, defaultGateway),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultGateway"
		},
	{ ATF_POINTER, 2, offsetof(struct Ipv6InterfaceInfo__Member, primaryDns),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"primaryDns"
		},
	{ ATF_POINTER, 1, offsetof(struct Ipv6InterfaceInfo__Member, gatewayMacAddress),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MACaddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gatewayMacAddress"
		},
};
static const int asn_MAP_Member_oms_2[] = { 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_Member_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interfaceName */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ipAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* macAddress */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* defaultGateway */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* primaryDns */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* gatewayMacAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_2 = {
	sizeof(struct Ipv6InterfaceInfo__Member),
	offsetof(struct Ipv6InterfaceInfo__Member, _asn_ctx),
	asn_MAP_Member_tag2el_2,
	6,	/* Count of tags in the map */
	asn_MAP_Member_oms_2,	/* Optional members */
	3, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_2 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_2,
	sizeof(asn_DEF_Member_tags_2)
		/sizeof(asn_DEF_Member_tags_2[0]), /* 1 */
	asn_DEF_Member_tags_2,	/* Same as above */
	sizeof(asn_DEF_Member_tags_2)
		/sizeof(asn_DEF_Member_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_2,
	6,	/* Elements count */
	&asn_SPC_Member_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Ipv6InterfaceInfo_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_Ipv6InterfaceInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_Ipv6InterfaceInfo_specs_1 = {
	sizeof(struct Ipv6InterfaceInfo),
	offsetof(struct Ipv6InterfaceInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_Ipv6InterfaceInfo = {
	"Ipv6InterfaceInfo",
	"Ipv6InterfaceInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_Ipv6InterfaceInfo_tags_1,
	sizeof(asn_DEF_Ipv6InterfaceInfo_tags_1)
		/sizeof(asn_DEF_Ipv6InterfaceInfo_tags_1[0]), /* 1 */
	asn_DEF_Ipv6InterfaceInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ipv6InterfaceInfo_tags_1)
		/sizeof(asn_DEF_Ipv6InterfaceInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_Ipv6InterfaceInfo_1,
	1,	/* Single element */
	&asn_SPC_Ipv6InterfaceInfo_specs_1	/* Additional specs */
};

