/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_IPv6RxRecord_H_
#define	_IPv6RxRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include <UTF8String.h>
#include "ServicePort.h"
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IPv6RxRecord__protocol {
	IPv6RxRecord__protocol_tcp	= 0,
	IPv6RxRecord__protocol_udp	= 1
} e_IPv6RxRecord__protocol;

/* Forward declarations */
struct EventHandling;

/* IPv6RxRecord */
typedef struct IPv6RxRecord {
	RadioInterface_t	 radio;
	UTF8String_t	 interfaceName;
	ServicePort_t	 listenPort;
	ENUMERATED_t	 protocol;
	struct EventHandling	*eventHandling	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPv6RxRecord_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_protocol_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IPv6RxRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_IPv6RxRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_IPv6RxRecord_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EventHandling.h"

#endif	/* _IPv6RxRecord_H_ */
#include <asn_internal.h>
