/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-responseInfo"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Ipv6InterfaceInfo_H_
#define	_Ipv6InterfaceInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <UTF8String.h>
#include "MACaddress.h"
#include "IPv6Address.h"
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct Ipv6InterfaceInfo__Member {
	UTF8String_t	 interfaceName;
	struct Ipv6InterfaceInfo__Member__ipAddress {
		A_SEQUENCE_OF(IPv6Address_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ipAddress;
	MACaddress_t	 macAddress;
	IPv6Address_t	*defaultGateway	/* OPTIONAL */;
	IPv6Address_t	*primaryDns	/* OPTIONAL */;
	MACaddress_t	*gatewayMacAddress	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ipv6InterfaceInfo__Member;

/* Ipv6InterfaceInfo */
typedef struct Ipv6InterfaceInfo {
	A_SEQUENCE_OF(Ipv6InterfaceInfo__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ipv6InterfaceInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ipv6InterfaceInfo;
extern asn_SET_OF_specifics_t asn_SPC_Ipv6InterfaceInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_Ipv6InterfaceInfo_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _Ipv6InterfaceInfo_H_ */
#include <asn_internal.h>
