/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_IPv6TxRecord_H_
#define	_IPv6TxRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include <UTF8String.h>
#include "IPv6Address.h"
#include "ServicePort.h"
#include <ENUMERATED.h>
#include "RepeatRate.h"
#include "Opaque.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IPv6TxRecord__protocol {
	IPv6TxRecord__protocol_tcp	= 0,
	IPv6TxRecord__protocol_udp	= 1,
	IPv6TxRecord__protocol_icmp	= 2
} e_IPv6TxRecord__protocol;

/* Forward declarations */
struct EventHandling;

/* IPv6TxRecord */
typedef struct IPv6TxRecord {
	RadioInterface_t	 radio;
	UTF8String_t	 interfaceName;
	IPv6Address_t	 destIpAddress;
	ServicePort_t	*destPort	/* OPTIONAL */;
	ENUMERATED_t	 protocol;
	RepeatRate_t	*repeatRate	/* OPTIONAL */;
	struct EventHandling	*eventHandling	/* OPTIONAL */;
	Opaque_t	*payload	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPv6TxRecord_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_protocol_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IPv6TxRecord;
extern asn_SEQUENCE_specifics_t asn_SPC_IPv6TxRecord_specs_1;
extern asn_TYPE_member_t asn_MBR_IPv6TxRecord_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EventHandling.h"

#endif	/* _IPv6TxRecord_H_ */
#include <asn_internal.h>
