/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "IPv6TxRecord.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static int
memb_interfaceName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 1 && size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_eventHandling_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_type_protocol_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_memb_interfaceName_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_oer_constraints_t asn_OER_memb_eventHandling_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_protocol_value2enum_6[] = {
	{ 0,	3,	"tcp" },
	{ 1,	3,	"udp" },
	{ 2,	4,	"icmp" }
};
static const unsigned int asn_MAP_protocol_enum2value_6[] = {
	2,	/* icmp(2) */
	0,	/* tcp(0) */
	1	/* udp(1) */
};
static const asn_INTEGER_specifics_t asn_SPC_protocol_specs_6 = {
	asn_MAP_protocol_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_protocol_enum2value_6,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_protocol_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_protocol_6 = {
	"protocol",
	"protocol",
	&asn_OP_ENUMERATED,
	asn_DEF_protocol_tags_6,
	sizeof(asn_DEF_protocol_tags_6)
		/sizeof(asn_DEF_protocol_tags_6[0]) - 1, /* 1 */
	asn_DEF_protocol_tags_6,	/* Same as above */
	sizeof(asn_DEF_protocol_tags_6)
		/sizeof(asn_DEF_protocol_tags_6[0]), /* 2 */
	{ &asn_OER_type_protocol_constr_6, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_protocol_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_IPv6TxRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IPv6TxRecord, radio),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPv6TxRecord, interfaceName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_interfaceName_constr_3, 0,  memb_interfaceName_constraint_1 },
		0, 0, /* No default value */
		"interfaceName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPv6TxRecord, destIpAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"destIpAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct IPv6TxRecord, destPort),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServicePort,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"destPort"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IPv6TxRecord, protocol),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_protocol_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocol"
		},
	{ ATF_POINTER, 3, offsetof(struct IPv6TxRecord, repeatRate),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RepeatRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"repeatRate"
		},
	{ ATF_POINTER, 2, offsetof(struct IPv6TxRecord, eventHandling),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventHandling,
		0,
		{ &asn_OER_memb_eventHandling_constr_11, 0,  memb_eventHandling_constraint_1 },
		0, 0, /* No default value */
		"eventHandling"
		},
	{ ATF_POINTER, 1, offsetof(struct IPv6TxRecord, payload),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"payload"
		},
};
static const int asn_MAP_IPv6TxRecord_oms_1[] = { 3, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_IPv6TxRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IPv6TxRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* interfaceName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* destIpAddress */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* destPort */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* protocol */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* repeatRate */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* eventHandling */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* payload */
};
asn_SEQUENCE_specifics_t asn_SPC_IPv6TxRecord_specs_1 = {
	sizeof(struct IPv6TxRecord),
	offsetof(struct IPv6TxRecord, _asn_ctx),
	asn_MAP_IPv6TxRecord_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_IPv6TxRecord_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IPv6TxRecord = {
	"IPv6TxRecord",
	"IPv6TxRecord",
	&asn_OP_SEQUENCE,
	asn_DEF_IPv6TxRecord_tags_1,
	sizeof(asn_DEF_IPv6TxRecord_tags_1)
		/sizeof(asn_DEF_IPv6TxRecord_tags_1[0]), /* 1 */
	asn_DEF_IPv6TxRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPv6TxRecord_tags_1)
		/sizeof(asn_DEF_IPv6TxRecord_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IPv6TxRecord_1,
	8,	/* Elements count */
	&asn_SPC_IPv6TxRecord_specs_1	/* Additional specs */
};

