/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Module_H_
#define	_Module_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Module */
typedef UTF8String_t	 Module_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Module;
asn_struct_free_f Module_free;
asn_struct_print_f Module_print;
asn_constr_check_f Module_constraint;
ber_type_decoder_f Module_decode_ber;
der_type_encoder_f Module_encode_der;
xer_type_decoder_f Module_decode_xer;
xer_type_encoder_f Module_encode_xer;
oer_type_decoder_f Module_decode_oer;
oer_type_encoder_f Module_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Module_H_ */
#include <asn_internal.h>
