/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_MsgID_H_
#define	_MsgID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MsgID */
typedef long	 MsgID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsgID;
asn_struct_free_f MsgID_free;
asn_struct_print_f MsgID_print;
asn_constr_check_f MsgID_constraint;
ber_type_decoder_f MsgID_decode_ber;
der_type_encoder_f MsgID_encode_der;
xer_type_decoder_f MsgID_decode_xer;
xer_type_encoder_f MsgID_encode_xer;
oer_type_decoder_f MsgID_decode_oer;
oer_type_encoder_f MsgID_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _MsgID_H_ */
#include <asn_internal.h>
