/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_NullNetworking_H_
#define	_NullNetworking_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ShortMsgVersion.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ShortMsgNextensions;

/* NullNetworking */
typedef struct NullNetworking {
	ShortMsgVersion_t	 version;
	struct ShortMsgNextensions	*nExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NullNetworking_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NullNetworking;
extern asn_SEQUENCE_specifics_t asn_SPC_NullNetworking_specs_1;
extern asn_TYPE_member_t asn_MBR_NullNetworking_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ShortMsgNextensions.h"

#endif	/* _NullNetworking_H_ */
#include <asn_internal.h>
