/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Pdu_H_
#define	_Pdu_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PduType.h"
#include "PduData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Pdu */
typedef struct Pdu {
	PduType_t	 pduType;
	PduData_t	 pduData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Pdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Pdu;
extern asn_SEQUENCE_specifics_t asn_SPC_Pdu_specs_1;
extern asn_TYPE_member_t asn_MBR_Pdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Pdu_H_ */
#include <asn_internal.h>
