/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_VarLengthNumber2;
extern struct asn_TYPE_descriptor_s asn_DEF_ProviderMacAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_RcpiThreshold;
extern struct asn_TYPE_descriptor_s asn_DEF_WsaCountThreshold;
extern struct asn_TYPE_descriptor_s asn_DEF_WsaCountThresholdInterval;
extern struct asn_TYPE_descriptor_s asn_DEF_ChannelAccess80211;
extern struct asn_TYPE_descriptor_s asn_DEF_SecondaryDns;
extern struct asn_TYPE_descriptor_s asn_DEF_GatewayMacAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_SrvAdvMsg;
extern struct asn_TYPE_descriptor_s asn_DEF_ShortMsgNpdu;
extern struct asn_TYPE_descriptor_s asn_DEF_DummyExtension;
extern struct asn_TYPE_descriptor_s asn_DEF_TCIMsg;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CITSapplMgmtIDs in TCI.asn1 */
	&asn_DEF_VarLengthNumber2,	
	/* From module IEEE-1609-3-WEE in TCI.asn1 */
	&asn_DEF_ProviderMacAddress,	
	&asn_DEF_RcpiThreshold,	
	&asn_DEF_WsaCountThreshold,	
	&asn_DEF_WsaCountThresholdInterval,	
	&asn_DEF_ChannelAccess80211,	
	&asn_DEF_SecondaryDns,	
	&asn_DEF_GatewayMacAddress,	
	/* From module IEEE-1609-3-WSA in TCI.asn1 */
	&asn_DEF_SrvAdvMsg,	
	/* From module IEEE-1609-3-WSM in TCI.asn1 */
	&asn_DEF_ShortMsgNpdu,	
	&asn_DEF_DummyExtension,	
	/* From module TCI-Dispatcher in TCI.asn1 */
	&asn_DEF_TCIMsg,	
	0
};

