/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_PduData_H_
#define	_PduData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Opaque.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PduData */
typedef Opaque_t	 PduData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PduData;
asn_struct_free_f PduData_free;
asn_struct_print_f PduData_print;
asn_constr_check_f PduData_constraint;
ber_type_decoder_f PduData_decode_ber;
der_type_encoder_f PduData_encode_der;
xer_type_decoder_f PduData_decode_xer;
xer_type_encoder_f PduData_encode_xer;
oer_type_decoder_f PduData_decode_oer;
oer_type_encoder_f PduData_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _PduData_H_ */
#include <asn_internal.h>
