/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "ProviderServiceContext.h"

static int
memb_fillBit_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_psc_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 31)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_fillBit_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	3	/* (SIZE(3..3)) */};
static asn_oer_constraints_t asn_OER_memb_psc_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..31)) */};
asn_TYPE_member_t asn_MBR_ProviderServiceContext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProviderServiceContext, fillBit),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ &asn_OER_memb_fillBit_constr_2, 0,  memb_fillBit_constraint_1 },
		0, 0, /* No default value */
		"fillBit"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProviderServiceContext, psc),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_psc_constr_3, 0,  memb_psc_constraint_1 },
		0, 0, /* No default value */
		"psc"
		},
};
static const ber_tlv_tag_t asn_DEF_ProviderServiceContext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProviderServiceContext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fillBit */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* psc */
};
asn_SEQUENCE_specifics_t asn_SPC_ProviderServiceContext_specs_1 = {
	sizeof(struct ProviderServiceContext),
	offsetof(struct ProviderServiceContext, _asn_ctx),
	asn_MAP_ProviderServiceContext_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ProviderServiceContext = {
	"ProviderServiceContext",
	"ProviderServiceContext",
	&asn_OP_SEQUENCE,
	asn_DEF_ProviderServiceContext_tags_1,
	sizeof(asn_DEF_ProviderServiceContext_tags_1)
		/sizeof(asn_DEF_ProviderServiceContext_tags_1[0]), /* 1 */
	asn_DEF_ProviderServiceContext_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProviderServiceContext_tags_1)
		/sizeof(asn_DEF_ProviderServiceContext_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ProviderServiceContext_1,
	2,	/* Elements count */
	&asn_SPC_ProviderServiceContext_specs_1	/* Additional specs */
};

