/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ProviderMacAddress_H_
#define	_ProviderMacAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MACaddress.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProviderMacAddress */
typedef MACaddress_t	 ProviderMacAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProviderMacAddress;
asn_struct_free_f ProviderMacAddress_free;
asn_struct_print_f ProviderMacAddress_print;
asn_constr_check_f ProviderMacAddress_constraint;
ber_type_decoder_f ProviderMacAddress_decode_ber;
der_type_encoder_f ProviderMacAddress_encode_der;
xer_type_decoder_f ProviderMacAddress_decode_xer;
xer_type_encoder_f ProviderMacAddress_encode_xer;
oer_type_decoder_f ProviderMacAddress_decode_oer;
oer_type_encoder_f ProviderMacAddress_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ProviderMacAddress_H_ */
#include <asn_internal.h>
