/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "Psid.h"

/*
 * This type is implemented using VarLengthNumber,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Psid_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_descriptor_t asn_DEF_Psid = {
	"Psid",
	"Psid",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_VarLengthNumber_1,
	2,	/* Elements count */
	&asn_SPC_VarLengthNumber_specs_1	/* Additional specs */
};

