/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-CommonTypes"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_RCPI_H_
#define	_RCPI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RCPI */
typedef long	 RCPI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RCPI;
asn_struct_free_f RCPI_free;
asn_struct_print_f RCPI_print;
asn_constr_check_f RCPI_constraint;
ber_type_decoder_f RCPI_decode_ber;
der_type_encoder_f RCPI_encode_der;
xer_type_decoder_f RCPI_decode_xer;
xer_type_encoder_f RCPI_encode_xer;
oer_type_decoder_f RCPI_decode_oer;
oer_type_encoder_f RCPI_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _RCPI_H_ */
#include <asn_internal.h>
