/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "ReplyAddress.h"

/*
 * This type is implemented using NULL,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ReplyAddress_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (5 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ReplyAddress = {
	"ReplyAddress",
	"ReplyAddress",
	&asn_OP_NULL,
	asn_DEF_ReplyAddress_tags_1,
	sizeof(asn_DEF_ReplyAddress_tags_1)
		/sizeof(asn_DEF_ReplyAddress_tags_1[0]), /* 1 */
	asn_DEF_ReplyAddress_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReplyAddress_tags_1)
		/sizeof(asn_DEF_ReplyAddress_tags_1[0]), /* 1 */
	{ 0, 0, NULL_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

