/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ReplyAddress_H_
#define	_ReplyAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReplyAddress */
typedef NULL_t	 ReplyAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReplyAddress;
asn_struct_free_f ReplyAddress_free;
asn_struct_print_f ReplyAddress_print;
asn_constr_check_f ReplyAddress_constraint;
ber_type_decoder_f ReplyAddress_decode_ber;
der_type_encoder_f ReplyAddress_encode_der;
xer_type_decoder_f ReplyAddress_decode_xer;
xer_type_encoder_f ReplyAddress_encode_xer;
oer_type_decoder_f ReplyAddress_decode_oer;
oer_type_encoder_f ReplyAddress_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ReplyAddress_H_ */
#include <asn_internal.h>
