/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_RequestSutAvailability_H_
#define	_RequestSutAvailability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RequestSutAvailability */
typedef BOOLEAN_t	 RequestSutAvailability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequestSutAvailability;
asn_struct_free_f RequestSutAvailability_free;
asn_struct_print_f RequestSutAvailability_print;
asn_constr_check_f RequestSutAvailability_constraint;
ber_type_decoder_f RequestSutAvailability_decode_ber;
der_type_encoder_f RequestSutAvailability_encode_der;
xer_type_decoder_f RequestSutAvailability_decode_xer;
xer_type_encoder_f RequestSutAvailability_encode_xer;
oer_type_decoder_f RequestSutAvailability_decode_oer;
oer_type_encoder_f RequestSutAvailability_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _RequestSutAvailability_H_ */
#include <asn_internal.h>
