/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "RoutingAdvertisement.h"

asn_TYPE_member_t asn_MBR_RoutingAdvertisement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingAdvertisement, lifetime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RouterLifetime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lifetime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingAdvertisement, ipPrefix),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpV6Prefix,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipPrefix"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingAdvertisement, ipPrefixLength),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpV6PrefixLength,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipPrefixLength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingAdvertisement, defaultGateway),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultGateway"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingAdvertisement, primaryDns),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"primaryDns"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoutingAdvertisement, extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoutAdvertExts,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
};
static const ber_tlv_tag_t asn_DEF_RoutingAdvertisement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RoutingAdvertisement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lifetime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ipPrefix */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ipPrefixLength */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* defaultGateway */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* primaryDns */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_RoutingAdvertisement_specs_1 = {
	sizeof(struct RoutingAdvertisement),
	offsetof(struct RoutingAdvertisement, _asn_ctx),
	asn_MAP_RoutingAdvertisement_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RoutingAdvertisement = {
	"RoutingAdvertisement",
	"RoutingAdvertisement",
	&asn_OP_SEQUENCE,
	asn_DEF_RoutingAdvertisement_tags_1,
	sizeof(asn_DEF_RoutingAdvertisement_tags_1)
		/sizeof(asn_DEF_RoutingAdvertisement_tags_1[0]), /* 1 */
	asn_DEF_RoutingAdvertisement_tags_1,	/* Same as above */
	sizeof(asn_DEF_RoutingAdvertisement_tags_1)
		/sizeof(asn_DEF_RoutingAdvertisement_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RoutingAdvertisement_1,
	6,	/* Elements count */
	&asn_SPC_RoutingAdvertisement_specs_1	/* Additional specs */
};

