/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "RoutAdvertExt.h"

/*
 * This type is implemented using Extension_73P0,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_RoutAdvertExt_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_RoutAdvertExt = {
	"RoutAdvertExt",
	"RoutAdvertExt",
	&asn_OP_SEQUENCE,
	asn_DEF_RoutAdvertExt_tags_1,
	sizeof(asn_DEF_RoutAdvertExt_tags_1)
		/sizeof(asn_DEF_RoutAdvertExt_tags_1[0]), /* 1 */
	asn_DEF_RoutAdvertExt_tags_1,	/* Same as above */
	sizeof(asn_DEF_RoutAdvertExt_tags_1)
		/sizeof(asn_DEF_RoutAdvertExt_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Extension_73P0_1,
	2,	/* Elements count */
	&asn_SPC_Extension_73P0_specs_1	/* Additional specs */
};

