/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-eventHandling"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_RxFlag_H_
#define	_RxFlag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RxFlag {
	RxFlag_recvPsidMatch	= 0,
	RxFlag_includePdu	= 1,
	RxFlag_includePduParam	= 2
} e_RxFlag;

/* RxFlag */
typedef BIT_STRING_t	 RxFlag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RxFlag;
asn_struct_free_f RxFlag_free;
asn_struct_print_f RxFlag_print;
asn_constr_check_f RxFlag_constraint;
ber_type_decoder_f RxFlag_decode_ber;
der_type_encoder_f RxFlag_encode_der;
xer_type_decoder_f RxFlag_decode_xer;
xer_type_encoder_f RxFlag_encode_xer;
oer_type_decoder_f RxFlag_decode_oer;
oer_type_encoder_f RxFlag_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _RxFlag_H_ */
#include <asn_internal.h>
