/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SecResultParams.h"

asn_TYPE_member_t asn_MBR_SecResultParams_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SecResultParams, securityResultCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SecurityResultCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityResultCode"
		},
	{ ATF_POINTER, 1, offsetof(struct SecResultParams, description),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"description"
		},
};
static const int asn_MAP_SecResultParams_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_SecResultParams_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SecResultParams_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* securityResultCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* description */
};
asn_SEQUENCE_specifics_t asn_SPC_SecResultParams_specs_1 = {
	sizeof(struct SecResultParams),
	offsetof(struct SecResultParams, _asn_ctx),
	asn_MAP_SecResultParams_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_SecResultParams_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SecResultParams = {
	"SecResultParams",
	"SecResultParams",
	&asn_OP_SEQUENCE,
	asn_DEF_SecResultParams_tags_1,
	sizeof(asn_DEF_SecResultParams_tags_1)
		/sizeof(asn_DEF_SecResultParams_tags_1[0]), /* 1 */
	asn_DEF_SecResultParams_tags_1,	/* Same as above */
	sizeof(asn_DEF_SecResultParams_tags_1)
		/sizeof(asn_DEF_SecResultParams_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SecResultParams_1,
	2,	/* Elements count */
	&asn_SPC_SecResultParams_specs_1	/* Additional specs */
};

