/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-eventHandling"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SecurityFlag_H_
#define	_SecurityFlag_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityFlag {
	SecurityFlag_bypassSecurityVerification	= 0
} e_SecurityFlag;

/* SecurityFlag */
typedef BIT_STRING_t	 SecurityFlag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityFlag;
asn_struct_free_f SecurityFlag_free;
asn_struct_print_f SecurityFlag_print;
asn_constr_check_f SecurityFlag_constraint;
ber_type_decoder_f SecurityFlag_decode_ber;
der_type_encoder_f SecurityFlag_encode_der;
xer_type_decoder_f SecurityFlag_decode_xer;
xer_type_encoder_f SecurityFlag_encode_xer;
oer_type_decoder_f SecurityFlag_decode_oer;
oer_type_encoder_f SecurityFlag_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityFlag_H_ */
#include <asn_internal.h>
