/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ServiceInfoExt_H_
#define	_ServiceInfoExt_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Extension.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceInfoExt */
typedef Extension_73P0_t	 ServiceInfoExt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceInfoExt;
asn_struct_free_f ServiceInfoExt_free;
asn_struct_print_f ServiceInfoExt_print;
asn_constr_check_f ServiceInfoExt_constraint;
ber_type_decoder_f ServiceInfoExt_decode_ber;
der_type_encoder_f ServiceInfoExt_encode_der;
xer_type_decoder_f ServiceInfoExt_decode_xer;
xer_type_encoder_f ServiceInfoExt_encode_xer;
oer_type_decoder_f ServiceInfoExt_decode_oer;
oer_type_encoder_f ServiceInfoExt_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceInfoExt_H_ */
#include <asn_internal.h>
