/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ServiceInfos_H_
#define	_ServiceInfos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceInfo;

/* ServiceInfos */
typedef struct ServiceInfos {
	A_SEQUENCE_OF(struct ServiceInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceInfos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceInfos;
extern asn_SET_OF_specifics_t asn_SPC_ServiceInfos_specs_1;
extern asn_TYPE_member_t asn_MBR_ServiceInfos_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceInfo.h"

#endif	/* _ServiceInfos_H_ */
#include <asn_internal.h>
