/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "ServiceParameters.h"

static asn_TYPE_member_t asn_MBR_psid_2[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Psid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_psid_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_psid_specs_2 = {
	sizeof(struct ServiceParameters__psid),
	offsetof(struct ServiceParameters__psid, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_psid_2 = {
	"psid",
	"psid",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_psid_tags_2,
	sizeof(asn_DEF_psid_tags_2)
		/sizeof(asn_DEF_psid_tags_2[0]) - 1, /* 1 */
	asn_DEF_psid_tags_2,	/* Same as above */
	sizeof(asn_DEF_psid_tags_2)
		/sizeof(asn_DEF_psid_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_psid_2,
	1,	/* Single element */
	&asn_SPC_psid_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ServiceParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServiceParameters, psid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_psid_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"psid"
		},
};
static const ber_tlv_tag_t asn_DEF_ServiceParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ServiceParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* psid */
};
asn_SEQUENCE_specifics_t asn_SPC_ServiceParameters_specs_1 = {
	sizeof(struct ServiceParameters),
	offsetof(struct ServiceParameters, _asn_ctx),
	asn_MAP_ServiceParameters_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ServiceParameters = {
	"ServiceParameters",
	"ServiceParameters",
	&asn_OP_SEQUENCE,
	asn_DEF_ServiceParameters_tags_1,
	sizeof(asn_DEF_ServiceParameters_tags_1)
		/sizeof(asn_DEF_ServiceParameters_tags_1[0]), /* 1 */
	asn_DEF_ServiceParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServiceParameters_tags_1)
		/sizeof(asn_DEF_ServiceParameters_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ServiceParameters_1,
	1,	/* Elements count */
	&asn_SPC_ServiceParameters_specs_1	/* Additional specs */
};

