/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SetBrakeSystemStatus.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_tractionControlStatus_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_type_antiLockBrakeStatus_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_type_stabilityControlStatus_constr_18 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_type_brakeBoostApplied_constr_23 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_type_auxiliaryBrakeStatus_constr_27 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_tractionControlStatus_value2enum_8[] = {
	{ 0,	11,	"unavailable" },
	{ 1,	3,	"off" },
	{ 2,	2,	"on" },
	{ 3,	7,	"engaged" }
};
static const unsigned int asn_MAP_tractionControlStatus_enum2value_8[] = {
	3,	/* engaged(3) */
	1,	/* off(1) */
	2,	/* on(2) */
	0	/* unavailable(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_tractionControlStatus_specs_8 = {
	asn_MAP_tractionControlStatus_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_tractionControlStatus_enum2value_8,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_tractionControlStatus_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tractionControlStatus_8 = {
	"tractionControlStatus",
	"tractionControlStatus",
	&asn_OP_ENUMERATED,
	asn_DEF_tractionControlStatus_tags_8,
	sizeof(asn_DEF_tractionControlStatus_tags_8)
		/sizeof(asn_DEF_tractionControlStatus_tags_8[0]) - 1, /* 1 */
	asn_DEF_tractionControlStatus_tags_8,	/* Same as above */
	sizeof(asn_DEF_tractionControlStatus_tags_8)
		/sizeof(asn_DEF_tractionControlStatus_tags_8[0]), /* 2 */
	{ &asn_OER_type_tractionControlStatus_constr_8, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_tractionControlStatus_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_antiLockBrakeStatus_value2enum_13[] = {
	{ 0,	11,	"unavailable" },
	{ 1,	3,	"off" },
	{ 2,	2,	"on" },
	{ 3,	7,	"engaged" }
};
static const unsigned int asn_MAP_antiLockBrakeStatus_enum2value_13[] = {
	3,	/* engaged(3) */
	1,	/* off(1) */
	2,	/* on(2) */
	0	/* unavailable(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_antiLockBrakeStatus_specs_13 = {
	asn_MAP_antiLockBrakeStatus_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_antiLockBrakeStatus_enum2value_13,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_antiLockBrakeStatus_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_antiLockBrakeStatus_13 = {
	"antiLockBrakeStatus",
	"antiLockBrakeStatus",
	&asn_OP_ENUMERATED,
	asn_DEF_antiLockBrakeStatus_tags_13,
	sizeof(asn_DEF_antiLockBrakeStatus_tags_13)
		/sizeof(asn_DEF_antiLockBrakeStatus_tags_13[0]) - 1, /* 1 */
	asn_DEF_antiLockBrakeStatus_tags_13,	/* Same as above */
	sizeof(asn_DEF_antiLockBrakeStatus_tags_13)
		/sizeof(asn_DEF_antiLockBrakeStatus_tags_13[0]), /* 2 */
	{ &asn_OER_type_antiLockBrakeStatus_constr_13, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_antiLockBrakeStatus_specs_13	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_stabilityControlStatus_value2enum_18[] = {
	{ 0,	11,	"unavailable" },
	{ 1,	3,	"off" },
	{ 2,	2,	"on" },
	{ 3,	7,	"engaged" }
};
static const unsigned int asn_MAP_stabilityControlStatus_enum2value_18[] = {
	3,	/* engaged(3) */
	1,	/* off(1) */
	2,	/* on(2) */
	0	/* unavailable(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_stabilityControlStatus_specs_18 = {
	asn_MAP_stabilityControlStatus_value2enum_18,	/* "tag" => N; sorted by tag */
	asn_MAP_stabilityControlStatus_enum2value_18,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_stabilityControlStatus_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_stabilityControlStatus_18 = {
	"stabilityControlStatus",
	"stabilityControlStatus",
	&asn_OP_ENUMERATED,
	asn_DEF_stabilityControlStatus_tags_18,
	sizeof(asn_DEF_stabilityControlStatus_tags_18)
		/sizeof(asn_DEF_stabilityControlStatus_tags_18[0]) - 1, /* 1 */
	asn_DEF_stabilityControlStatus_tags_18,	/* Same as above */
	sizeof(asn_DEF_stabilityControlStatus_tags_18)
		/sizeof(asn_DEF_stabilityControlStatus_tags_18[0]), /* 2 */
	{ &asn_OER_type_stabilityControlStatus_constr_18, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_stabilityControlStatus_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_brakeBoostApplied_value2enum_23[] = {
	{ 0,	11,	"unavailable" },
	{ 1,	3,	"off" },
	{ 2,	2,	"on" }
};
static const unsigned int asn_MAP_brakeBoostApplied_enum2value_23[] = {
	1,	/* off(1) */
	2,	/* on(2) */
	0	/* unavailable(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_brakeBoostApplied_specs_23 = {
	asn_MAP_brakeBoostApplied_value2enum_23,	/* "tag" => N; sorted by tag */
	asn_MAP_brakeBoostApplied_enum2value_23,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_brakeBoostApplied_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_brakeBoostApplied_23 = {
	"brakeBoostApplied",
	"brakeBoostApplied",
	&asn_OP_ENUMERATED,
	asn_DEF_brakeBoostApplied_tags_23,
	sizeof(asn_DEF_brakeBoostApplied_tags_23)
		/sizeof(asn_DEF_brakeBoostApplied_tags_23[0]) - 1, /* 1 */
	asn_DEF_brakeBoostApplied_tags_23,	/* Same as above */
	sizeof(asn_DEF_brakeBoostApplied_tags_23)
		/sizeof(asn_DEF_brakeBoostApplied_tags_23[0]), /* 2 */
	{ &asn_OER_type_brakeBoostApplied_constr_23, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_brakeBoostApplied_specs_23	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_auxiliaryBrakeStatus_value2enum_27[] = {
	{ 0,	11,	"unavailable" },
	{ 1,	3,	"off" },
	{ 2,	2,	"on" },
	{ 3,	8,	"reserved" }
};
static const unsigned int asn_MAP_auxiliaryBrakeStatus_enum2value_27[] = {
	1,	/* off(1) */
	2,	/* on(2) */
	3,	/* reserved(3) */
	0	/* unavailable(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_auxiliaryBrakeStatus_specs_27 = {
	asn_MAP_auxiliaryBrakeStatus_value2enum_27,	/* "tag" => N; sorted by tag */
	asn_MAP_auxiliaryBrakeStatus_enum2value_27,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_auxiliaryBrakeStatus_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_auxiliaryBrakeStatus_27 = {
	"auxiliaryBrakeStatus",
	"auxiliaryBrakeStatus",
	&asn_OP_ENUMERATED,
	asn_DEF_auxiliaryBrakeStatus_tags_27,
	sizeof(asn_DEF_auxiliaryBrakeStatus_tags_27)
		/sizeof(asn_DEF_auxiliaryBrakeStatus_tags_27[0]) - 1, /* 1 */
	asn_DEF_auxiliaryBrakeStatus_tags_27,	/* Same as above */
	sizeof(asn_DEF_auxiliaryBrakeStatus_tags_27)
		/sizeof(asn_DEF_auxiliaryBrakeStatus_tags_27[0]), /* 2 */
	{ &asn_OER_type_auxiliaryBrakeStatus_constr_27, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_auxiliaryBrakeStatus_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SetBrakeSystemStatus_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetBrakeSystemStatus, brakeAppliedStatus),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"brakeAppliedStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetBrakeSystemStatus, tractionControlStatus),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_tractionControlStatus_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tractionControlStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetBrakeSystemStatus, antiLockBrakeStatus),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_antiLockBrakeStatus_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"antiLockBrakeStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetBrakeSystemStatus, stabilityControlStatus),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_stabilityControlStatus_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stabilityControlStatus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetBrakeSystemStatus, brakeBoostApplied),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_brakeBoostApplied_23,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"brakeBoostApplied"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetBrakeSystemStatus, auxiliaryBrakeStatus),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_auxiliaryBrakeStatus_27,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"auxiliaryBrakeStatus"
		},
};
static const ber_tlv_tag_t asn_DEF_SetBrakeSystemStatus_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetBrakeSystemStatus_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* brakeAppliedStatus */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* tractionControlStatus */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* antiLockBrakeStatus */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* stabilityControlStatus */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* brakeBoostApplied */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* auxiliaryBrakeStatus */
};
asn_SEQUENCE_specifics_t asn_SPC_SetBrakeSystemStatus_specs_1 = {
	sizeof(struct SetBrakeSystemStatus),
	offsetof(struct SetBrakeSystemStatus, _asn_ctx),
	asn_MAP_SetBrakeSystemStatus_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetBrakeSystemStatus = {
	"SetBrakeSystemStatus",
	"SetBrakeSystemStatus",
	&asn_OP_SEQUENCE,
	asn_DEF_SetBrakeSystemStatus_tags_1,
	sizeof(asn_DEF_SetBrakeSystemStatus_tags_1)
		/sizeof(asn_DEF_SetBrakeSystemStatus_tags_1[0]), /* 1 */
	asn_DEF_SetBrakeSystemStatus_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetBrakeSystemStatus_tags_1)
		/sizeof(asn_DEF_SetBrakeSystemStatus_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SetBrakeSystemStatus_1,
	6,	/* Elements count */
	&asn_SPC_SetBrakeSystemStatus_specs_1	/* Additional specs */
};

