/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SetIPv6Address_H_
#define	_SetIPv6Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include <UTF8String.h>
#include "IPv6Address.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetIPv6Address */
typedef struct SetIPv6Address {
	RadioInterface_t	 radio;
	UTF8String_t	 interfaceName;
	IPv6Address_t	*ipAddress	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetIPv6Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetIPv6Address;
extern asn_SEQUENCE_specifics_t asn_SPC_SetIPv6Address_specs_1;
extern asn_TYPE_member_t asn_MBR_SetIPv6Address_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SetIPv6Address_H_ */
#include <asn_internal.h>
