/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-ip"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SetIPv6Address.h"

static int
memb_radio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_interfaceName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 1 && size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_radio_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_memb_interfaceName_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
asn_TYPE_member_t asn_MBR_SetIPv6Address_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetIPv6Address, radio),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ &asn_OER_memb_radio_constr_2, 0,  memb_radio_constraint_1 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetIPv6Address, interfaceName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_interfaceName_constr_3, 0,  memb_interfaceName_constraint_1 },
		0, 0, /* No default value */
		"interfaceName"
		},
	{ ATF_POINTER, 1, offsetof(struct SetIPv6Address, ipAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IPv6Address,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipAddress"
		},
};
static const int asn_MAP_SetIPv6Address_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_SetIPv6Address_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetIPv6Address_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* interfaceName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ipAddress */
};
asn_SEQUENCE_specifics_t asn_SPC_SetIPv6Address_specs_1 = {
	sizeof(struct SetIPv6Address),
	offsetof(struct SetIPv6Address, _asn_ctx),
	asn_MAP_SetIPv6Address_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SetIPv6Address_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetIPv6Address = {
	"SetIPv6Address",
	"SetIPv6Address",
	&asn_OP_SEQUENCE,
	asn_DEF_SetIPv6Address_tags_1,
	sizeof(asn_DEF_SetIPv6Address_tags_1)
		/sizeof(asn_DEF_SetIPv6Address_tags_1[0]), /* 1 */
	asn_DEF_SetIPv6Address_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetIPv6Address_tags_1)
		/sizeof(asn_DEF_SetIPv6Address_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SetIPv6Address_1,
	3,	/* Elements count */
	&asn_SPC_SetIPv6Address_specs_1	/* Additional specs */
};

