/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SetLatitude_H_
#define	_SetLatitude_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Latitude.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SetLatitude */
typedef Latitude_t	 SetLatitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetLatitude;
asn_struct_free_f SetLatitude_free;
asn_struct_print_f SetLatitude_print;
asn_constr_check_f SetLatitude_constraint;
ber_type_decoder_f SetLatitude_decode_ber;
der_type_encoder_f SetLatitude_encode_der;
xer_type_decoder_f SetLatitude_decode_xer;
xer_type_encoder_f SetLatitude_encode_xer;
oer_type_decoder_f SetLatitude_decode_oer;
oer_type_encoder_f SetLatitude_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _SetLatitude_H_ */
#include <asn_internal.h>
