/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SetPositionalAccuracy_H_
#define	_SetPositionalAccuracy_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetPositionalAccuracy */
typedef struct SetPositionalAccuracy {
	long	 semiMajorAxisAccuracy;
	long	 semiMinorAxisAccuracy;
	long	 semiMajorAxisOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetPositionalAccuracy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetPositionalAccuracy;
extern asn_SEQUENCE_specifics_t asn_SPC_SetPositionalAccuracy_specs_1;
extern asn_TYPE_member_t asn_MBR_SetPositionalAccuracy_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SetPositionalAccuracy_H_ */
#include <asn_internal.h>
