/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SetTestId_H_
#define	_SetTestId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetTestId */
typedef UTF8String_t	 SetTestId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetTestId;
asn_struct_free_f SetTestId_free;
asn_struct_print_f SetTestId_print;
asn_constr_check_f SetTestId_constraint;
ber_type_decoder_f SetTestId_decode_ber;
der_type_encoder_f SetTestId_encode_der;
xer_type_decoder_f SetTestId_decode_xer;
xer_type_encoder_f SetTestId_encode_xer;
oer_type_decoder_f SetTestId_decode_oer;
oer_type_encoder_f SetTestId_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _SetTestId_H_ */
#include <asn_internal.h>
