/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SetTransmissionState.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_SetTransmissionState_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_SetTransmissionState_value2enum_1[] = {
	{ 0,	7,	"neutral" },
	{ 1,	4,	"park" },
	{ 2,	12,	"forwardGears" },
	{ 3,	12,	"reverseGears" },
	{ 4,	9,	"reserved1" },
	{ 5,	9,	"reserved2" },
	{ 6,	9,	"reserved3" },
	{ 7,	11,	"unavailable" }
};
static const unsigned int asn_MAP_SetTransmissionState_enum2value_1[] = {
	2,	/* forwardGears(2) */
	0,	/* neutral(0) */
	1,	/* park(1) */
	4,	/* reserved1(4) */
	5,	/* reserved2(5) */
	6,	/* reserved3(6) */
	3,	/* reverseGears(3) */
	7	/* unavailable(7) */
};
const asn_INTEGER_specifics_t asn_SPC_SetTransmissionState_specs_1 = {
	asn_MAP_SetTransmissionState_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SetTransmissionState_enum2value_1,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SetTransmissionState_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SetTransmissionState = {
	"SetTransmissionState",
	"SetTransmissionState",
	&asn_OP_ENUMERATED,
	asn_DEF_SetTransmissionState_tags_1,
	sizeof(asn_DEF_SetTransmissionState_tags_1)
		/sizeof(asn_DEF_SetTransmissionState_tags_1[0]), /* 1 */
	asn_DEF_SetTransmissionState_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetTransmissionState_tags_1)
		/sizeof(asn_DEF_SetTransmissionState_tags_1[0]), /* 1 */
	{ &asn_OER_type_SetTransmissionState_constr_1, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SetTransmissionState_specs_1	/* Additional specs */
};

