/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SetVehicleSize.h"

static int
memb_vehicleWidth_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_vehicleLength_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 4095)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_vehicleWidth_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (0..1023) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_vehicleLength_constr_3 CC_NOTUSED = {
	{ 2, 1 }	/* (0..4095) */,
	-1};
asn_TYPE_member_t asn_MBR_SetVehicleSize_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetVehicleSize, vehicleWidth),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_vehicleWidth_constr_2, 0,  memb_vehicleWidth_constraint_1 },
		0, 0, /* No default value */
		"vehicleWidth"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetVehicleSize, vehicleLength),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_vehicleLength_constr_3, 0,  memb_vehicleLength_constraint_1 },
		0, 0, /* No default value */
		"vehicleLength"
		},
};
static const ber_tlv_tag_t asn_DEF_SetVehicleSize_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetVehicleSize_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* vehicleWidth */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* vehicleLength */
};
asn_SEQUENCE_specifics_t asn_SPC_SetVehicleSize_specs_1 = {
	sizeof(struct SetVehicleSize),
	offsetof(struct SetVehicleSize, _asn_ctx),
	asn_MAP_SetVehicleSize_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetVehicleSize = {
	"SetVehicleSize",
	"SetVehicleSize",
	&asn_OP_SEQUENCE,
	asn_DEF_SetVehicleSize_tags_1,
	sizeof(asn_DEF_SetVehicleSize_tags_1)
		/sizeof(asn_DEF_SetVehicleSize_tags_1[0]), /* 1 */
	asn_DEF_SetVehicleSize_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetVehicleSize_tags_1)
		/sizeof(asn_DEF_SetVehicleSize_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SetVehicleSize_1,
	2,	/* Elements count */
	&asn_SPC_SetVehicleSize_specs_1	/* Additional specs */
};

