/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SetWsmTxInfo.h"

asn_TYPE_member_t asn_MBR_SetWsmTxInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, psid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Psid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"psid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, radio),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, security),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SecurityContext,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"security"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, channelIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelNumber80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, timeslot),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeSlot,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeslot"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, dataRate),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataRate80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, transmitPowerLevel),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TXpower80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transmitPowerLevel"
		},
	{ ATF_POINTER, 1, offsetof(struct SetWsmTxInfo, infoElementsIncluded),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WaveElementsIncluded,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"infoElementsIncluded"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetWsmTxInfo, userPriority),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserPriority,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userPriority"
		},
	{ ATF_POINTER, 5, offsetof(struct SetWsmTxInfo, destinationMACAddr),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MACaddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"destinationMACAddr"
		},
	{ ATF_POINTER, 4, offsetof(struct SetWsmTxInfo, expiryTime),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Time64,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"expiryTime"
		},
	{ ATF_POINTER, 3, offsetof(struct SetWsmTxInfo, channelLoad),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelLoad"
		},
	{ ATF_POINTER, 2, offsetof(struct SetWsmTxInfo, repeatRate),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RepeatRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"repeatRate"
		},
	{ ATF_POINTER, 1, offsetof(struct SetWsmTxInfo, payload),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Opaque,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"payload"
		},
};
static const int asn_MAP_SetWsmTxInfo_oms_1[] = { 7, 9, 10, 11, 12, 13 };
static const ber_tlv_tag_t asn_DEF_SetWsmTxInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetWsmTxInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* psid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* security */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* channelIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* timeslot */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* dataRate */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* transmitPowerLevel */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* infoElementsIncluded */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* userPriority */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* destinationMACAddr */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* expiryTime */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* channelLoad */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* repeatRate */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 } /* payload */
};
asn_SEQUENCE_specifics_t asn_SPC_SetWsmTxInfo_specs_1 = {
	sizeof(struct SetWsmTxInfo),
	offsetof(struct SetWsmTxInfo, _asn_ctx),
	asn_MAP_SetWsmTxInfo_tag2el_1,
	14,	/* Count of tags in the map */
	asn_MAP_SetWsmTxInfo_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	14,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetWsmTxInfo = {
	"SetWsmTxInfo",
	"SetWsmTxInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SetWsmTxInfo_tags_1,
	sizeof(asn_DEF_SetWsmTxInfo_tags_1)
		/sizeof(asn_DEF_SetWsmTxInfo_tags_1[0]), /* 1 */
	asn_DEF_SetWsmTxInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetWsmTxInfo_tags_1)
		/sizeof(asn_DEF_SetWsmTxInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SetWsmTxInfo_1,
	14,	/* Elements count */
	&asn_SPC_SetWsmTxInfo_specs_1	/* Additional specs */
};

