/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SetWsmTxInfo_H_
#define	_SetWsmTxInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Psid.h"
#include "RadioInterface.h"
#include "SecurityContext.h"
#include "ChannelNumber80211.h"
#include "TimeSlot.h"
#include "DataRate80211.h"
#include "TXpower80211.h"
#include "WaveElementsIncluded.h"
#include "UserPriority.h"
#include "MACaddress.h"
#include "Time64.h"
#include "Opaque.h"
#include "RepeatRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetWsmTxInfo */
typedef struct SetWsmTxInfo {
	Psid_t	 psid;
	RadioInterface_t	 radio;
	SecurityContext_t	 security;
	ChannelNumber80211_t	 channelIdentifier;
	TimeSlot_t	 timeslot;
	DataRate80211_t	 dataRate;
	TXpower80211_t	 transmitPowerLevel;
	WaveElementsIncluded_t	*infoElementsIncluded	/* DEFAULT '000000'HH */;
	UserPriority_t	 userPriority;
	MACaddress_t	*destinationMACAddr	/* DEFAULT 'FFFFFFFFFFFF'HHet4Way */;
	Time64_t	*expiryTime	/* OPTIONAL */;
	Opaque_t	*channelLoad	/* OPTIONAL */;
	RepeatRate_t	*repeatRate	/* OPTIONAL */;
	Opaque_t	*payload	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetWsmTxInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetWsmTxInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SetWsmTxInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SetWsmTxInfo_1[14];

#ifdef __cplusplus
}
#endif

#endif	/* _SetWsmTxInfo_H_ */
#include <asn_internal.h>
