/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ShortMsgTpdus_H_
#define	_ShortMsgTpdus_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ShortMsgBcPDU.h"
#include "NoTpidProcessing.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ShortMsgTpdus_PR {
	ShortMsgTpdus_PR_NOTHING,	/* No components present */
	ShortMsgTpdus_PR_bcMode,
	ShortMsgTpdus_PR_tpidReserved1,
	ShortMsgTpdus_PR_tpidReserved2,
	ShortMsgTpdus_PR_tpidReserved3,
	ShortMsgTpdus_PR_tpidReserved4,
	ShortMsgTpdus_PR_tpidReserved5,
	ShortMsgTpdus_PR_tpidReserved6,
	ShortMsgTpdus_PR_tpidReserved7,
	ShortMsgTpdus_PR_tpidReserved8,
	ShortMsgTpdus_PR_tpidReserved9,
	ShortMsgTpdus_PR_tpidReserved10,
	ShortMsgTpdus_PR_tpidReserved11,
	ShortMsgTpdus_PR_tpidReserved12,
	ShortMsgTpdus_PR_tpidReserved13,
	ShortMsgTpdus_PR_tpidReserved14,
	ShortMsgTpdus_PR_tpidReserved15,
	ShortMsgTpdus_PR_tpidReserved16,
	ShortMsgTpdus_PR_tpidReserved17,
	ShortMsgTpdus_PR_tpidReserved18,
	ShortMsgTpdus_PR_tpidReserved19,
	ShortMsgTpdus_PR_tpidReserved20,
	ShortMsgTpdus_PR_tpidReserved21,
	ShortMsgTpdus_PR_tpidReserved22,
	ShortMsgTpdus_PR_tpidReserved23,
	ShortMsgTpdus_PR_tpidReserved24,
	ShortMsgTpdus_PR_tpidReserved25,
	ShortMsgTpdus_PR_tpidReserved26,
	ShortMsgTpdus_PR_tpidReserved27,
	ShortMsgTpdus_PR_tpidReserved28,
	ShortMsgTpdus_PR_tpidReserved29,
	ShortMsgTpdus_PR_tpidReserved30,
	ShortMsgTpdus_PR_tpidReserved31,
	ShortMsgTpdus_PR_tpidReserved32,
	ShortMsgTpdus_PR_tpidReserved33,
	ShortMsgTpdus_PR_tpidReserved34,
	ShortMsgTpdus_PR_tpidReserved35,
	ShortMsgTpdus_PR_tpidReserved36,
	ShortMsgTpdus_PR_tpidReserved37,
	ShortMsgTpdus_PR_tpidReserved38,
	ShortMsgTpdus_PR_tpidReserved39,
	ShortMsgTpdus_PR_tpidReserved40,
	ShortMsgTpdus_PR_tpidReserved41,
	ShortMsgTpdus_PR_tpidReserved42,
	ShortMsgTpdus_PR_tpidReserved43,
	ShortMsgTpdus_PR_tpidReserved44,
	ShortMsgTpdus_PR_tpidReserved45,
	ShortMsgTpdus_PR_tpidReserved46,
	ShortMsgTpdus_PR_tpidReserved47,
	ShortMsgTpdus_PR_tpidReserved48,
	ShortMsgTpdus_PR_tpidReserved49,
	ShortMsgTpdus_PR_tpidReserved50,
	ShortMsgTpdus_PR_tpidReserved51,
	ShortMsgTpdus_PR_tpidReserved52,
	ShortMsgTpdus_PR_tpidReserved53,
	ShortMsgTpdus_PR_tpidReserved54,
	ShortMsgTpdus_PR_tpidReserved55,
	ShortMsgTpdus_PR_tpidReserved56,
	ShortMsgTpdus_PR_tpidReserved57,
	ShortMsgTpdus_PR_tpidReserved58,
	ShortMsgTpdus_PR_tpidReserved59,
	ShortMsgTpdus_PR_tpidReserved60,
	ShortMsgTpdus_PR_tpidReserved61,
	ShortMsgTpdus_PR_tpidReserved62,
	ShortMsgTpdus_PR_tpidReserved63,
	ShortMsgTpdus_PR_tpidReserved64,
	ShortMsgTpdus_PR_tpidReserved65,
	ShortMsgTpdus_PR_tpidReserved66,
	ShortMsgTpdus_PR_tpidReserved67,
	ShortMsgTpdus_PR_tpidReserved68,
	ShortMsgTpdus_PR_tpidReserved69,
	ShortMsgTpdus_PR_tpidReserved70,
	ShortMsgTpdus_PR_tpidReserved71,
	ShortMsgTpdus_PR_tpidReserved72,
	ShortMsgTpdus_PR_tpidReserved73,
	ShortMsgTpdus_PR_tpidReserved74,
	ShortMsgTpdus_PR_tpidReserved75,
	ShortMsgTpdus_PR_tpidReserved76,
	ShortMsgTpdus_PR_tpidReserved77,
	ShortMsgTpdus_PR_tpidReserved78,
	ShortMsgTpdus_PR_tpidReserved79,
	ShortMsgTpdus_PR_tpidReserved80,
	ShortMsgTpdus_PR_tpidReserved81,
	ShortMsgTpdus_PR_tpidReserved82,
	ShortMsgTpdus_PR_tpidReserved83,
	ShortMsgTpdus_PR_tpidReserved84,
	ShortMsgTpdus_PR_tpidReserved85,
	ShortMsgTpdus_PR_tpidReserved86,
	ShortMsgTpdus_PR_tpidReserved87,
	ShortMsgTpdus_PR_tpidReserved88,
	ShortMsgTpdus_PR_tpidReserved89,
	ShortMsgTpdus_PR_tpidReserved90,
	ShortMsgTpdus_PR_tpidReserved91,
	ShortMsgTpdus_PR_tpidReserved92,
	ShortMsgTpdus_PR_tpidReserved93,
	ShortMsgTpdus_PR_tpidReserved94,
	ShortMsgTpdus_PR_tpidReserved95,
	ShortMsgTpdus_PR_tpidReserved96,
	ShortMsgTpdus_PR_tpidReserved97,
	ShortMsgTpdus_PR_tpidReserved98,
	ShortMsgTpdus_PR_tpidReserved99,
	ShortMsgTpdus_PR_tpidReserved100,
	ShortMsgTpdus_PR_tpidReserved101,
	ShortMsgTpdus_PR_tpidReserved102,
	ShortMsgTpdus_PR_tpidReserved103,
	ShortMsgTpdus_PR_tpidReserved104,
	ShortMsgTpdus_PR_tpidReserved105,
	ShortMsgTpdus_PR_tpidReserved106,
	ShortMsgTpdus_PR_tpidReserved107,
	ShortMsgTpdus_PR_tpidReserved108,
	ShortMsgTpdus_PR_tpidReserved109,
	ShortMsgTpdus_PR_tpidReserved110,
	ShortMsgTpdus_PR_tpidReserved111,
	ShortMsgTpdus_PR_tpidReserved112,
	ShortMsgTpdus_PR_tpidReserved113,
	ShortMsgTpdus_PR_tpidReserved114,
	ShortMsgTpdus_PR_tpidReserved115,
	ShortMsgTpdus_PR_tpidReserved116,
	ShortMsgTpdus_PR_tpidReserved117,
	ShortMsgTpdus_PR_tpidReserved118,
	ShortMsgTpdus_PR_tpidReserved119,
	ShortMsgTpdus_PR_tpidReserved120,
	ShortMsgTpdus_PR_tpidReserved121,
	ShortMsgTpdus_PR_tpidReserved122,
	ShortMsgTpdus_PR_tpidReserved123,
	ShortMsgTpdus_PR_tpidReserved124,
	ShortMsgTpdus_PR_tpidReserved125,
	ShortMsgTpdus_PR_tpidReserved126,
	ShortMsgTpdus_PR_tpidReserved127
} ShortMsgTpdus_PR;

/* ShortMsgTpdus */
typedef struct ShortMsgTpdus {
	ShortMsgTpdus_PR present;
	union ShortMsgTpdus_u {
		ShortMsgBcPDU_t	 bcMode;
		NoTpidProcessing_t	 tpidReserved1;
		NoTpidProcessing_t	 tpidReserved2;
		NoTpidProcessing_t	 tpidReserved3;
		NoTpidProcessing_t	 tpidReserved4;
		NoTpidProcessing_t	 tpidReserved5;
		NoTpidProcessing_t	 tpidReserved6;
		NoTpidProcessing_t	 tpidReserved7;
		NoTpidProcessing_t	 tpidReserved8;
		NoTpidProcessing_t	 tpidReserved9;
		NoTpidProcessing_t	 tpidReserved10;
		NoTpidProcessing_t	 tpidReserved11;
		NoTpidProcessing_t	 tpidReserved12;
		NoTpidProcessing_t	 tpidReserved13;
		NoTpidProcessing_t	 tpidReserved14;
		NoTpidProcessing_t	 tpidReserved15;
		NoTpidProcessing_t	 tpidReserved16;
		NoTpidProcessing_t	 tpidReserved17;
		NoTpidProcessing_t	 tpidReserved18;
		NoTpidProcessing_t	 tpidReserved19;
		NoTpidProcessing_t	 tpidReserved20;
		NoTpidProcessing_t	 tpidReserved21;
		NoTpidProcessing_t	 tpidReserved22;
		NoTpidProcessing_t	 tpidReserved23;
		NoTpidProcessing_t	 tpidReserved24;
		NoTpidProcessing_t	 tpidReserved25;
		NoTpidProcessing_t	 tpidReserved26;
		NoTpidProcessing_t	 tpidReserved27;
		NoTpidProcessing_t	 tpidReserved28;
		NoTpidProcessing_t	 tpidReserved29;
		NoTpidProcessing_t	 tpidReserved30;
		NoTpidProcessing_t	 tpidReserved31;
		NoTpidProcessing_t	 tpidReserved32;
		NoTpidProcessing_t	 tpidReserved33;
		NoTpidProcessing_t	 tpidReserved34;
		NoTpidProcessing_t	 tpidReserved35;
		NoTpidProcessing_t	 tpidReserved36;
		NoTpidProcessing_t	 tpidReserved37;
		NoTpidProcessing_t	 tpidReserved38;
		NoTpidProcessing_t	 tpidReserved39;
		NoTpidProcessing_t	 tpidReserved40;
		NoTpidProcessing_t	 tpidReserved41;
		NoTpidProcessing_t	 tpidReserved42;
		NoTpidProcessing_t	 tpidReserved43;
		NoTpidProcessing_t	 tpidReserved44;
		NoTpidProcessing_t	 tpidReserved45;
		NoTpidProcessing_t	 tpidReserved46;
		NoTpidProcessing_t	 tpidReserved47;
		NoTpidProcessing_t	 tpidReserved48;
		NoTpidProcessing_t	 tpidReserved49;
		NoTpidProcessing_t	 tpidReserved50;
		NoTpidProcessing_t	 tpidReserved51;
		NoTpidProcessing_t	 tpidReserved52;
		NoTpidProcessing_t	 tpidReserved53;
		NoTpidProcessing_t	 tpidReserved54;
		NoTpidProcessing_t	 tpidReserved55;
		NoTpidProcessing_t	 tpidReserved56;
		NoTpidProcessing_t	 tpidReserved57;
		NoTpidProcessing_t	 tpidReserved58;
		NoTpidProcessing_t	 tpidReserved59;
		NoTpidProcessing_t	 tpidReserved60;
		NoTpidProcessing_t	 tpidReserved61;
		NoTpidProcessing_t	 tpidReserved62;
		NoTpidProcessing_t	 tpidReserved63;
		NoTpidProcessing_t	 tpidReserved64;
		NoTpidProcessing_t	 tpidReserved65;
		NoTpidProcessing_t	 tpidReserved66;
		NoTpidProcessing_t	 tpidReserved67;
		NoTpidProcessing_t	 tpidReserved68;
		NoTpidProcessing_t	 tpidReserved69;
		NoTpidProcessing_t	 tpidReserved70;
		NoTpidProcessing_t	 tpidReserved71;
		NoTpidProcessing_t	 tpidReserved72;
		NoTpidProcessing_t	 tpidReserved73;
		NoTpidProcessing_t	 tpidReserved74;
		NoTpidProcessing_t	 tpidReserved75;
		NoTpidProcessing_t	 tpidReserved76;
		NoTpidProcessing_t	 tpidReserved77;
		NoTpidProcessing_t	 tpidReserved78;
		NoTpidProcessing_t	 tpidReserved79;
		NoTpidProcessing_t	 tpidReserved80;
		NoTpidProcessing_t	 tpidReserved81;
		NoTpidProcessing_t	 tpidReserved82;
		NoTpidProcessing_t	 tpidReserved83;
		NoTpidProcessing_t	 tpidReserved84;
		NoTpidProcessing_t	 tpidReserved85;
		NoTpidProcessing_t	 tpidReserved86;
		NoTpidProcessing_t	 tpidReserved87;
		NoTpidProcessing_t	 tpidReserved88;
		NoTpidProcessing_t	 tpidReserved89;
		NoTpidProcessing_t	 tpidReserved90;
		NoTpidProcessing_t	 tpidReserved91;
		NoTpidProcessing_t	 tpidReserved92;
		NoTpidProcessing_t	 tpidReserved93;
		NoTpidProcessing_t	 tpidReserved94;
		NoTpidProcessing_t	 tpidReserved95;
		NoTpidProcessing_t	 tpidReserved96;
		NoTpidProcessing_t	 tpidReserved97;
		NoTpidProcessing_t	 tpidReserved98;
		NoTpidProcessing_t	 tpidReserved99;
		NoTpidProcessing_t	 tpidReserved100;
		NoTpidProcessing_t	 tpidReserved101;
		NoTpidProcessing_t	 tpidReserved102;
		NoTpidProcessing_t	 tpidReserved103;
		NoTpidProcessing_t	 tpidReserved104;
		NoTpidProcessing_t	 tpidReserved105;
		NoTpidProcessing_t	 tpidReserved106;
		NoTpidProcessing_t	 tpidReserved107;
		NoTpidProcessing_t	 tpidReserved108;
		NoTpidProcessing_t	 tpidReserved109;
		NoTpidProcessing_t	 tpidReserved110;
		NoTpidProcessing_t	 tpidReserved111;
		NoTpidProcessing_t	 tpidReserved112;
		NoTpidProcessing_t	 tpidReserved113;
		NoTpidProcessing_t	 tpidReserved114;
		NoTpidProcessing_t	 tpidReserved115;
		NoTpidProcessing_t	 tpidReserved116;
		NoTpidProcessing_t	 tpidReserved117;
		NoTpidProcessing_t	 tpidReserved118;
		NoTpidProcessing_t	 tpidReserved119;
		NoTpidProcessing_t	 tpidReserved120;
		NoTpidProcessing_t	 tpidReserved121;
		NoTpidProcessing_t	 tpidReserved122;
		NoTpidProcessing_t	 tpidReserved123;
		NoTpidProcessing_t	 tpidReserved124;
		NoTpidProcessing_t	 tpidReserved125;
		NoTpidProcessing_t	 tpidReserved126;
		NoTpidProcessing_t	 tpidReserved127;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShortMsgTpdus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShortMsgTpdus;
extern asn_CHOICE_specifics_t asn_SPC_ShortMsgTpdus_specs_1;
extern asn_TYPE_member_t asn_MBR_ShortMsgTpdus_1[128];

#ifdef __cplusplus
}
#endif

#endif	/* _ShortMsgTpdus_H_ */
#include <asn_internal.h>
