/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ShortMsgTextensions_H_
#define	_ShortMsgTextensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ShortMsgTextension;

/* ShortMsgTextensions */
typedef struct ShortMsgTextensions {
	A_SEQUENCE_OF(struct ShortMsgTextension) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShortMsgTextensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShortMsgTextensions;
extern asn_SET_OF_specifics_t asn_SPC_ShortMsgTextensions_specs_1;
extern asn_TYPE_member_t asn_MBR_ShortMsgTextensions_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ShortMsgTextension.h"

#endif	/* _ShortMsgTextensions_H_ */
#include <asn_internal.h>
