/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ShortMsgBcPDU_H_
#define	_ShortMsgBcPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VarLengthNumber.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ShortMsgTextensions;

/* ShortMsgBcPDU */
typedef struct ShortMsgBcPDU {
	VarLengthNumber_t	 destAddress;
	struct ShortMsgTextensions	*tExtensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShortMsgBcPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShortMsgBcPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_ShortMsgBcPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_ShortMsgBcPDU_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ShortMsgTextensions.h"

#endif	/* _ShortMsgBcPDU_H_ */
#include <asn_internal.h>
