/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ShortMsgSubtype_H_
#define	_ShortMsgSubtype_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NullNetworking.h"
#include "NoSubtypeProcessing.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ShortMsgSubtype_PR {
	ShortMsgSubtype_PR_NOTHING,	/* No components present */
	ShortMsgSubtype_PR_nullNetworking,
	ShortMsgSubtype_PR_subTypeReserved1,
	ShortMsgSubtype_PR_subTypeReserved2,
	ShortMsgSubtype_PR_subTypeReserved3,
	ShortMsgSubtype_PR_subTypeReserved4,
	ShortMsgSubtype_PR_subTypeReserved5,
	ShortMsgSubtype_PR_subTypeReserved6,
	ShortMsgSubtype_PR_subTypeReserved7,
	ShortMsgSubtype_PR_subTypeReserved8,
	ShortMsgSubtype_PR_subTypeReserved9,
	ShortMsgSubtype_PR_subTypeReserved19,
	ShortMsgSubtype_PR_subTypeReserved11,
	ShortMsgSubtype_PR_subTypeReserved12,
	ShortMsgSubtype_PR_subTypeReserved13,
	ShortMsgSubtype_PR_subTypeReserved14,
	ShortMsgSubtype_PR_subTypeReserved15
} ShortMsgSubtype_PR;

/* ShortMsgSubtype */
typedef struct ShortMsgSubtype {
	ShortMsgSubtype_PR present;
	union ShortMsgSubtype_u {
		NullNetworking_t	 nullNetworking;
		NoSubtypeProcessing_t	 subTypeReserved1;
		NoSubtypeProcessing_t	 subTypeReserved2;
		NoSubtypeProcessing_t	 subTypeReserved3;
		NoSubtypeProcessing_t	 subTypeReserved4;
		NoSubtypeProcessing_t	 subTypeReserved5;
		NoSubtypeProcessing_t	 subTypeReserved6;
		NoSubtypeProcessing_t	 subTypeReserved7;
		NoSubtypeProcessing_t	 subTypeReserved8;
		NoSubtypeProcessing_t	 subTypeReserved9;
		NoSubtypeProcessing_t	 subTypeReserved19;
		NoSubtypeProcessing_t	 subTypeReserved11;
		NoSubtypeProcessing_t	 subTypeReserved12;
		NoSubtypeProcessing_t	 subTypeReserved13;
		NoSubtypeProcessing_t	 subTypeReserved14;
		NoSubtypeProcessing_t	 subTypeReserved15;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ShortMsgSubtype_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShortMsgSubtype;
extern asn_CHOICE_specifics_t asn_SPC_ShortMsgSubtype_specs_1;
extern asn_TYPE_member_t asn_MBR_ShortMsgSubtype_1[16];

#ifdef __cplusplus
}
#endif

#endif	/* _ShortMsgSubtype_H_ */
#include <asn_internal.h>
