/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ShortMsgNextension_H_
#define	_ShortMsgNextension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Extension.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ShortMsgNextension */
typedef Extension_73P0_t	 ShortMsgNextension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShortMsgNextension;
asn_struct_free_f ShortMsgNextension_free;
asn_struct_print_f ShortMsgNextension_print;
asn_constr_check_f ShortMsgNextension_constraint;
ber_type_decoder_f ShortMsgNextension_decode_ber;
der_type_encoder_f ShortMsgNextension_encode_der;
xer_type_decoder_f ShortMsgNextension_decode_xer;
xer_type_encoder_f ShortMsgNextension_encode_xer;
oer_type_decoder_f ShortMsgNextension_decode_oer;
oer_type_encoder_f ShortMsgNextension_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ShortMsgNextension_H_ */
#include <asn_internal.h>
