/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSM"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_ShortMsgData_H_
#define	_ShortMsgData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ShortMsgData */
typedef OCTET_STRING_t	 ShortMsgData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShortMsgData;
asn_struct_free_f ShortMsgData_free;
asn_struct_print_f ShortMsgData_print;
asn_constr_check_f ShortMsgData_constraint;
ber_type_decoder_f ShortMsgData_decode_ber;
der_type_encoder_f ShortMsgData_encode_der;
xer_type_decoder_f ShortMsgData_decode_xer;
xer_type_encoder_f ShortMsgData_encode_xer;
oer_type_decoder_f ShortMsgData_decode_oer;
oer_type_encoder_f ShortMsgData_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _ShortMsgData_H_ */
#include <asn_internal.h>
