/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_Shutdown_H_
#define	_Shutdown_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Shutdown */
typedef BOOLEAN_t	 Shutdown_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Shutdown;
asn_struct_free_f Shutdown_free;
asn_struct_print_f Shutdown_print;
asn_constr_check_f Shutdown_constraint;
ber_type_decoder_f Shutdown_decode_ber;
der_type_encoder_f Shutdown_encode_der;
xer_type_decoder_f Shutdown_decode_xer;
xer_type_encoder_f Shutdown_encode_xer;
oer_type_decoder_f Shutdown_decode_oer;
oer_type_encoder_f Shutdown_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _Shutdown_H_ */
#include <asn_internal.h>
