/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SignerIdentifierType.h"

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_SignerIdentifierType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static const asn_INTEGER_enum_map_t asn_MAP_SignerIdentifierType_value2enum_1[] = {
	{ 0,	8,	"unSecure" },
	{ 1,	27,	"useSecProfilePerContentType" },
	{ 2,	22,	"signIncludeCertificate" },
	{ 3,	17,	"signIncludeDigest" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_SignerIdentifierType_enum2value_1[] = {
	2,	/* signIncludeCertificate(2) */
	3,	/* signIncludeDigest(3) */
	0,	/* unSecure(0) */
	1	/* useSecProfilePerContentType(1) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_SignerIdentifierType_specs_1 = {
	asn_MAP_SignerIdentifierType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_SignerIdentifierType_enum2value_1,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	5,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_SignerIdentifierType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SignerIdentifierType = {
	"SignerIdentifierType",
	"SignerIdentifierType",
	&asn_OP_ENUMERATED,
	asn_DEF_SignerIdentifierType_tags_1,
	sizeof(asn_DEF_SignerIdentifierType_tags_1)
		/sizeof(asn_DEF_SignerIdentifierType_tags_1[0]), /* 1 */
	asn_DEF_SignerIdentifierType_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignerIdentifierType_tags_1)
		/sizeof(asn_DEF_SignerIdentifierType_tags_1[0]), /* 1 */
	{ &asn_OER_type_SignerIdentifierType_constr_1, 0, ENUMERATED_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_SignerIdentifierType_specs_1	/* Additional specs */
};

