/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SrvAdvMessageType_H_
#define	_SrvAdvMessageType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SrvAdvMessageType {
	SrvAdvMessageType_saMessage	= 0,
	SrvAdvMessageType_sarMessage	= 1
} e_SrvAdvMessageType;

/* SrvAdvMessageType */
typedef long	 SrvAdvMessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SrvAdvMessageType;
asn_struct_free_f SrvAdvMessageType_free;
asn_struct_print_f SrvAdvMessageType_print;
asn_constr_check_f SrvAdvMessageType_constraint;
ber_type_decoder_f SrvAdvMessageType_decode_ber;
der_type_encoder_f SrvAdvMessageType_encode_der;
xer_type_decoder_f SrvAdvMessageType_decode_xer;
xer_type_encoder_f SrvAdvMessageType_encode_xer;
oer_type_decoder_f SrvAdvMessageType_decode_oer;
oer_type_encoder_f SrvAdvMessageType_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _SrvAdvMessageType_H_ */
#include <asn_internal.h>
