/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WSA"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SrvAdvBody.h"

asn_TYPE_member_t asn_MBR_SrvAdvBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SrvAdvBody, changeCount),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SrvAdvChangeCount,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"changeCount"
		},
	{ ATF_POINTER, 4, offsetof(struct SrvAdvBody, extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SrvAdvMsgHeaderExts,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extensions"
		},
	{ ATF_POINTER, 3, offsetof(struct SrvAdvBody, serviceInfos),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ServiceInfos,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceInfos"
		},
	{ ATF_POINTER, 2, offsetof(struct SrvAdvBody, channelInfos),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelInfos,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelInfos"
		},
	{ ATF_POINTER, 1, offsetof(struct SrvAdvBody, routingAdvertisement),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoutingAdvertisement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"routingAdvertisement"
		},
};
static const int asn_MAP_SrvAdvBody_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SrvAdvBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SrvAdvBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* changeCount */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* extensions */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* serviceInfos */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* channelInfos */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* routingAdvertisement */
};
asn_SEQUENCE_specifics_t asn_SPC_SrvAdvBody_specs_1 = {
	sizeof(struct SrvAdvBody),
	offsetof(struct SrvAdvBody, _asn_ctx),
	asn_MAP_SrvAdvBody_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SrvAdvBody_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SrvAdvBody = {
	"SrvAdvBody",
	"SrvAdvBody",
	&asn_OP_SEQUENCE,
	asn_DEF_SrvAdvBody_tags_1,
	sizeof(asn_DEF_SrvAdvBody_tags_1)
		/sizeof(asn_DEF_SrvAdvBody_tags_1[0]), /* 1 */
	asn_DEF_SrvAdvBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_SrvAdvBody_tags_1)
		/sizeof(asn_DEF_SrvAdvBody_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SrvAdvBody_1,
	5,	/* Elements count */
	&asn_SPC_SrvAdvBody_specs_1	/* Additional specs */
};

