/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "StartWsaTxPerdiodic.h"

static int
memb_security_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_signatureLifetime_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 10 && value <= 30000)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_security_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_memb_signatureLifetime_constr_9 CC_NOTUSED = {
	{ 2, 1 }	/* (10..30000) */,
	-1};
asn_TYPE_member_t asn_MBR_StartWsaTxPerdiodic_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, radio),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_POINTER, 1, offsetof(struct StartWsaTxPerdiodic, destinationMACAddr),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MACaddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"destinationMACAddr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, wsaChannelIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelNumber80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wsaChannelIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, channelAccess),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeSlot,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelAccess"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, repeatRate),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RepeatRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"repeatRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, ipService),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, security),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SecurityContext,
		0,
		{ &asn_OER_memb_security_constr_8, 0,  memb_security_constraint_1 },
		0, 0, /* No default value */
		"security"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, signatureLifetime),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_signatureLifetime_constr_9, 0,  memb_signatureLifetime_constraint_1 },
		0, 0, /* No default value */
		"signatureLifetime"
		},
	{ ATF_POINTER, 2, offsetof(struct StartWsaTxPerdiodic, infoElementIncluded),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WaveElementsIncluded,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"infoElementIncluded"
		},
	{ ATF_POINTER, 1, offsetof(struct StartWsaTxPerdiodic, advertiserId),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdvertiserIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"advertiserId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, serviceInfos),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WsmServiceInfos,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceInfos"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StartWsaTxPerdiodic, channelinfos),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelInfos,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelinfos"
		},
	{ ATF_POINTER, 4, offsetof(struct StartWsaTxPerdiodic, wra),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoutingAdvertisement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"wra"
		},
	{ ATF_POINTER, 3, offsetof(struct StartWsaTxPerdiodic, dataRate),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataRate80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataRate"
		},
	{ ATF_POINTER, 2, offsetof(struct StartWsaTxPerdiodic, userPriority),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserPriority,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userPriority"
		},
	{ ATF_POINTER, 1, offsetof(struct StartWsaTxPerdiodic, transmitPowerLevel),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TXpower80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transmitPowerLevel"
		},
};
static const int asn_MAP_StartWsaTxPerdiodic_oms_1[] = { 1, 8, 9, 12, 13, 14, 15 };
static const ber_tlv_tag_t asn_DEF_StartWsaTxPerdiodic_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StartWsaTxPerdiodic_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* destinationMACAddr */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* wsaChannelIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* channelAccess */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* repeatRate */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ipService */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* security */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* signatureLifetime */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* infoElementIncluded */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* advertiserId */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* serviceInfos */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* channelinfos */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* wra */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* dataRate */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* userPriority */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 } /* transmitPowerLevel */
};
asn_SEQUENCE_specifics_t asn_SPC_StartWsaTxPerdiodic_specs_1 = {
	sizeof(struct StartWsaTxPerdiodic),
	offsetof(struct StartWsaTxPerdiodic, _asn_ctx),
	asn_MAP_StartWsaTxPerdiodic_tag2el_1,
	16,	/* Count of tags in the map */
	asn_MAP_StartWsaTxPerdiodic_oms_1,	/* Optional members */
	7, 0,	/* Root/Additions */
	16,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StartWsaTxPerdiodic = {
	"StartWsaTxPerdiodic",
	"StartWsaTxPerdiodic",
	&asn_OP_SEQUENCE,
	asn_DEF_StartWsaTxPerdiodic_tags_1,
	sizeof(asn_DEF_StartWsaTxPerdiodic_tags_1)
		/sizeof(asn_DEF_StartWsaTxPerdiodic_tags_1[0]), /* 1 */
	asn_DEF_StartWsaTxPerdiodic_tags_1,	/* Same as above */
	sizeof(asn_DEF_StartWsaTxPerdiodic_tags_1)
		/sizeof(asn_DEF_StartWsaTxPerdiodic_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_StartWsaTxPerdiodic_1,
	16,	/* Elements count */
	&asn_SPC_StartWsaTxPerdiodic_specs_1	/* Additional specs */
};

