/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_StartWsaTxPerdiodic_H_
#define	_StartWsaTxPerdiodic_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include "MACaddress.h"
#include "ChannelNumber80211.h"
#include "TimeSlot.h"
#include "RepeatRate.h"
#include <BOOLEAN.h>
#include "SecurityContext.h"
#include <NativeInteger.h>
#include "WaveElementsIncluded.h"
#include "AdvertiserIdentifier.h"
#include "WsmServiceInfos.h"
#include "ChannelInfos.h"
#include "DataRate80211.h"
#include "UserPriority.h"
#include "TXpower80211.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RoutingAdvertisement;

/* StartWsaTxPerdiodic */
typedef struct StartWsaTxPerdiodic {
	RadioInterface_t	 radio;
	MACaddress_t	*destinationMACAddr	/* DEFAULT 'FFFFFFFFFFFF'HHet4Way */;
	ChannelNumber80211_t	 wsaChannelIdentifier;
	TimeSlot_t	 channelAccess;
	RepeatRate_t	 repeatRate;
	BOOLEAN_t	 ipService;
	SecurityContext_t	 security;
	long	 signatureLifetime;
	WaveElementsIncluded_t	*infoElementIncluded	/* DEFAULT '000000'HHFFF'HHet4Way */;
	AdvertiserIdentifier_t	*advertiserId	/* OPTIONAL */;
	WsmServiceInfos_t	 serviceInfos;
	ChannelInfos_t	 channelinfos;
	struct RoutingAdvertisement	*wra	/* OPTIONAL */;
	DataRate80211_t	*dataRate	/* OPTIONAL */;
	UserPriority_t	*userPriority	/* OPTIONAL */;
	TXpower80211_t	*transmitPowerLevel	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartWsaTxPerdiodic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartWsaTxPerdiodic;
extern asn_SEQUENCE_specifics_t asn_SPC_StartWsaTxPerdiodic_specs_1;
extern asn_TYPE_member_t asn_MBR_StartWsaTxPerdiodic_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RoutingAdvertisement.h"

#endif	/* _StartWsaTxPerdiodic_H_ */
#include <asn_internal.h>
