/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_StartWsmRx_H_
#define	_StartWsmRx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RadioInterface.h"
#include "ChannelNumber80211.h"
#include "TimeSlot.h"
#include "EventHandling.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Psid;

/* StartWsmRx */
typedef struct StartWsmRx {
	struct Psid	*psid	/* OPTIONAL */;
	RadioInterface_t	 radio;
	ChannelNumber80211_t	 channelIdentifier;
	TimeSlot_t	 timeSlot;
	EventHandling_t	 eventHandling;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StartWsmRx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartWsmRx;
extern asn_SEQUENCE_specifics_t asn_SPC_StartWsmRx_specs_1;
extern asn_TYPE_member_t asn_MBR_StartWsmRx_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Psid.h"

#endif	/* _StartWsmRx_H_ */
#include <asn_internal.h>
