/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_StartBsmTx_H_
#define	_StartBsmTx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StartWsmTx.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StartBsmTx */
typedef StartWsmTx_t	 StartBsmTx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartBsmTx;
asn_struct_free_f StartBsmTx_free;
asn_struct_print_f StartBsmTx_print;
asn_constr_check_f StartBsmTx_constraint;
ber_type_decoder_f StartBsmTx_decode_ber;
der_type_encoder_f StartBsmTx_encode_der;
xer_type_decoder_f StartBsmTx_decode_xer;
xer_type_encoder_f StartBsmTx_encode_xer;
oer_type_decoder_f StartBsmTx_decode_oer;
oer_type_encoder_f StartBsmTx_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _StartBsmTx_H_ */
#include <asn_internal.h>
