/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_StartBsmRx_H_
#define	_StartBsmRx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StartWsmRx.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StartBsmRx */
typedef StartWsmRx_t	 StartBsmRx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StartBsmRx;
asn_struct_free_f StartBsmRx_free;
asn_struct_print_f StartBsmRx_print;
asn_constr_check_f StartBsmRx_constraint;
ber_type_decoder_f StartBsmRx_decode_ber;
der_type_encoder_f StartBsmRx_encode_der;
xer_type_decoder_f StartBsmRx_decode_xer;
xer_type_encoder_f StartBsmRx_encode_xer;
oer_type_decoder_f StartBsmRx_decode_oer;
oer_type_encoder_f StartBsmRx_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _StartBsmRx_H_ */
#include <asn_internal.h>
