/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_StopBsmTx_H_
#define	_StopBsmTx_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StopWsmTx.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StopBsmTx */
typedef StopWsmTx_t	 StopBsmTx_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StopBsmTx;
asn_struct_free_f StopBsmTx_free;
asn_struct_print_f StopBsmTx_print;
asn_constr_check_f StopBsmTx_constraint;
ber_type_decoder_f StopBsmTx_decode_ber;
der_type_encoder_f StopBsmTx_encode_der;
xer_type_decoder_f StopBsmTx_decode_xer;
xer_type_encoder_f StopBsmTx_encode_xer;
oer_type_decoder_f StopBsmTx_decode_oer;
oer_type_encoder_f StopBsmTx_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _StopBsmTx_H_ */
#include <asn_internal.h>
