/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "SutRequest.h"

static const long asn_VAL_1_shutdown = 1;
static const long asn_VAL_2_restart = 2;
static const long asn_VAL_3_requestSutAvailability = 3;
static const long asn_VAL_4_requestSutInfo = 4;
static const long asn_VAL_5_setTestId = 5;
static const long asn_VAL_6_enableGpsInput = 6;
static const long asn_VAL_7_setLatitude = 7;
static const long asn_VAL_8_setLongitude = 8;
static const long asn_VAL_9_setElevation = 9;
static const long asn_VAL_10_setPositionalAccuracy = 10;
static const long asn_VAL_11_setSpeed = 11;
static const long asn_VAL_12_setHeading = 12;
static const long asn_VAL_13_setAccelerationSet4Way = 13;
static const long asn_VAL_14_setGpsTime = 14;
static const asn_ioc_cell_t asn_IOS_SutMessageTypes_1_rows[] = {
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_1_shutdown },
	{ "&Type", aioc__type, &asn_DEF_Shutdown },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_2_restart },
	{ "&Type", aioc__type, &asn_DEF_Restart },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_3_requestSutAvailability },
	{ "&Type", aioc__type, &asn_DEF_RequestSutAvailability },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_4_requestSutInfo },
	{ "&Type", aioc__type, &asn_DEF_RequestSutInfo },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_5_setTestId },
	{ "&Type", aioc__type, &asn_DEF_SetTestId },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_6_enableGpsInput },
	{ "&Type", aioc__type, &asn_DEF_EnableGpsInput },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_7_setLatitude },
	{ "&Type", aioc__type, &asn_DEF_SetLatitude },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_8_setLongitude },
	{ "&Type", aioc__type, &asn_DEF_SetLongitude },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_9_setElevation },
	{ "&Type", aioc__type, &asn_DEF_SetElevation },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_10_setPositionalAccuracy },
	{ "&Type", aioc__type, &asn_DEF_SetPositionalAccuracy },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_11_setSpeed },
	{ "&Type", aioc__type, &asn_DEF_SetSpeed },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_12_setHeading },
	{ "&Type", aioc__type, &asn_DEF_SetHeading },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_13_setAccelerationSet4Way },
	{ "&Type", aioc__type, &asn_DEF_SetAccelerationSet4Way },
	{ "&id", aioc__value, &asn_DEF_MsgID, &asn_VAL_14_setGpsTime },
	{ "&Type", aioc__type, &asn_DEF_SetGpsTime }
};
static const asn_ioc_set_t asn_IOS_SutMessageTypes_1[] = {
	14, 2, asn_IOS_SutMessageTypes_1_rows
};
static int
memb_messageId_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_SutRequest_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_SutMessageTypes_1;
	size_t constraining_column = 0; /* &id */
	size_t for_column = 1; /* &Type */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct SutRequest, messageId));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_oer_constraints_t asn_OER_memb_messageId_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (0..255) */,
	-1};
static asn_oer_constraints_t asn_OER_memb_value_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_TYPE_member_t asn_MBR_value_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.Shutdown),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_Shutdown,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Shutdown"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.Restart),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_Restart,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"Restart"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.RequestSutAvailability),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_RequestSutAvailability,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RequestSutAvailability"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.RequestSutInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_RequestSutInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RequestSutInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetTestId),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_SetTestId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetTestId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.EnableGpsInput),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_EnableGpsInput,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"EnableGpsInput"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetLatitude),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetLatitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetLatitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetLongitude),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetLongitude,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetLongitude"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetElevation),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetElevation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetElevation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetPositionalAccuracy),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetPositionalAccuracy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetPositionalAccuracy"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetSpeed),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetSpeed,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetSpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetHeading),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetHeading,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetHeading"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetAccelerationSet4Way),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SetAccelerationSet4Way,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetAccelerationSet4Way"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest__value, choice.SetGpsTime),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_SetGpsTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SetGpsTime"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 4 }, /* Shutdown */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, -1, 3 }, /* Restart */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 2, -2, 2 }, /* RequestSutAvailability */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 3, -3, 1 }, /* RequestSutInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 5, -4, 0 }, /* EnableGpsInput */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 7, 0, 4 }, /* SetLongitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 8, -1, 3 }, /* SetElevation */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 10, -2, 2 }, /* SetSpeed */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 11, -3, 1 }, /* SetHeading */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 13, -4, 0 }, /* SetGpsTime */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 4, 0, 0 }, /* SetTestId */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, 0, 2 }, /* SetLatitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -1, 1 }, /* SetPositionalAccuracy */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -2, 0 } /* SetAccelerationSet4Way */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_3 = {
	sizeof(struct SutRequest__value),
	offsetof(struct SutRequest__value, _asn_ctx),
	offsetof(struct SutRequest__value, present),
	sizeof(((struct SutRequest__value *)0)->present),
	asn_MAP_value_tag2el_3,
	14,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_3 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_3,
	14,	/* Elements count */
	&asn_SPC_value_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SutRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SutRequest, messageId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsgID,
		0,
		{ &asn_OER_memb_messageId_constr_2, 0,  memb_messageId_constraint_1 },
		0, 0, /* No default value */
		"messageId"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct SutRequest, value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_3,
		select_SutRequest_value_type,
		{ &asn_OER_memb_value_constr_3, 0,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_SutRequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SutRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* messageId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_SutRequest_specs_1 = {
	sizeof(struct SutRequest),
	offsetof(struct SutRequest, _asn_ctx),
	asn_MAP_SutRequest_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SutRequest = {
	"SutRequest",
	"SutRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_SutRequest_tags_1,
	sizeof(asn_DEF_SutRequest_tags_1)
		/sizeof(asn_DEF_SutRequest_tags_1[0]), /* 1 */
	asn_DEF_SutRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_SutRequest_tags_1)
		/sizeof(asn_DEF_SutRequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SutRequest_1,
	2,	/* Elements count */
	&asn_SPC_SutRequest_specs_1	/* Additional specs */
};

