/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SutRequest_H_
#define	_SutRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "Shutdown.h"
#include "Restart.h"
#include "RequestSutAvailability.h"
#include "RequestSutInfo.h"
#include "SetTestId.h"
#include "EnableGpsInput.h"
#include "SetLatitude.h"
#include "SetLongitude.h"
#include "SetElevation.h"
#include "SetPositionalAccuracy.h"
#include "SetSpeed.h"
#include "SetHeading.h"
#include "SetAccelerationSet4Way.h"
#include "SetGpsTime.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SutRequest__value_PR {
	SutRequest__value_PR_NOTHING,	/* No components present */
	SutRequest__value_PR_Shutdown,
	SutRequest__value_PR_Restart,
	SutRequest__value_PR_RequestSutAvailability,
	SutRequest__value_PR_RequestSutInfo,
	SutRequest__value_PR_SetTestId,
	SutRequest__value_PR_EnableGpsInput,
	SutRequest__value_PR_SetLatitude,
	SutRequest__value_PR_SetLongitude,
	SutRequest__value_PR_SetElevation,
	SutRequest__value_PR_SetPositionalAccuracy,
	SutRequest__value_PR_SetSpeed,
	SutRequest__value_PR_SetHeading,
	SutRequest__value_PR_SetAccelerationSet4Way,
	SutRequest__value_PR_SetGpsTime
} SutRequest__value_PR;

/* SutRequest */
typedef struct SutRequest {
	MsgID_t	 messageId;
	struct SutRequest__value {
		SutRequest__value_PR present;
		union SutRequest__value_u {
			Shutdown_t	 Shutdown;
			Restart_t	 Restart;
			RequestSutAvailability_t	 RequestSutAvailability;
			RequestSutInfo_t	 RequestSutInfo;
			SetTestId_t	 SetTestId;
			EnableGpsInput_t	 EnableGpsInput;
			SetLatitude_t	 SetLatitude;
			SetLongitude_t	 SetLongitude;
			SetElevation_t	 SetElevation;
			SetPositionalAccuracy_t	 SetPositionalAccuracy;
			SetSpeed_t	 SetSpeed;
			SetHeading_t	 SetHeading;
			SetAccelerationSet4Way_t	 SetAccelerationSet4Way;
			SetGpsTime_t	 SetGpsTime;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SutRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SutRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SutRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SutRequest_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SutRequest_H_ */
#include <asn_internal.h>
