/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_SutResponseInfo_H_
#define	_SutResponseInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ResponseInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SutResponseInfo */
typedef ResponseInfo_t	 SutResponseInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SutResponseInfo;
asn_struct_free_f SutResponseInfo_free;
asn_struct_print_f SutResponseInfo_print;
asn_constr_check_f SutResponseInfo_constraint;
ber_type_decoder_f SutResponseInfo_decode_ber;
der_type_encoder_f SutResponseInfo_encode_der;
xer_type_decoder_f SutResponseInfo_decode_xer;
xer_type_encoder_f SutResponseInfo_encode_xer;
oer_type_decoder_f SutResponseInfo_decode_oer;
oer_type_encoder_f SutResponseInfo_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _SutResponseInfo_H_ */
#include <asn_internal.h>
