/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16093"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "TCI16093.h"

static asn_oer_constraints_t asn_OER_type_TCI16093_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_TYPE_member_t asn_MBR_TCI16093_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TCI16093, choice.request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Dot3Request,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TCI16093, choice.response),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Response,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TCI16093, choice.indication),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Dot3Indication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"indication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TCI16093, choice.responseInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Dot3ResponseInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"responseInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TCI16093, choice.exception),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Exception,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"exception"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TCI16093_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* request */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* response */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* indication */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* responseInfo */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* exception */
};
asn_CHOICE_specifics_t asn_SPC_TCI16093_specs_1 = {
	sizeof(struct TCI16093),
	offsetof(struct TCI16093, _asn_ctx),
	offsetof(struct TCI16093, present),
	sizeof(((struct TCI16093 *)0)->present),
	asn_MAP_TCI16093_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TCI16093 = {
	"TCI16093",
	"TCI16093",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TCI16093_constr_1, 0, CHOICE_constraint },
	asn_MBR_TCI16093_1,
	5,	/* Elements count */
	&asn_SPC_TCI16093_specs_1	/* Additional specs */
};

