/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16093"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TCI16093_H_
#define	_TCI16093_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Dot3Request.h"
#include "Response.h"
#include "Dot3Indication.h"
#include "Dot3ResponseInfo.h"
#include "Exception.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCI16093_PR {
	TCI16093_PR_NOTHING,	/* No components present */
	TCI16093_PR_request,
	TCI16093_PR_response,
	TCI16093_PR_indication,
	TCI16093_PR_responseInfo,
	TCI16093_PR_exception
	/* Extensions may appear below */
	
} TCI16093_PR;

/* TCI16093 */
typedef struct TCI16093 {
	TCI16093_PR present;
	union TCI16093_u {
		Dot3Request_t	 request;
		Response_t	 response;
		Dot3Indication_t	 indication;
		Dot3ResponseInfo_t	 responseInfo;
		Exception_t	 exception;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCI16093_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCI16093;
extern asn_CHOICE_specifics_t asn_SPC_TCI16093_specs_1;
extern asn_TYPE_member_t asn_MBR_TCI16093_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TCI16093_H_ */
#include <asn_internal.h>
