/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-16094"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TCI16094_H_
#define	_TCI16094_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Dot4Request.h"
#include "Response.h"
#include "Dot4Indication.h"
#include "Dot4ResponseInfo.h"
#include "Exception.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCI16094_PR {
	TCI16094_PR_NOTHING,	/* No components present */
	TCI16094_PR_request,
	TCI16094_PR_response,
	TCI16094_PR_indication,
	TCI16094_PR_responseInfo,
	TCI16094_PR_exception
	/* Extensions may appear below */
	
} TCI16094_PR;

/* TCI16094 */
typedef struct TCI16094 {
	TCI16094_PR present;
	union TCI16094_u {
		Dot4Request_t	 request;
		Response_t	 response;
		Dot4Indication_t	 indication;
		Dot4ResponseInfo_t	 responseInfo;
		Exception_t	 exception;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCI16094_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCI16094;
extern asn_CHOICE_specifics_t asn_SPC_TCI16094_specs_1;
extern asn_TYPE_member_t asn_MBR_TCI16094_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TCI16094_H_ */
#include <asn_internal.h>
