/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-29451"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TCI29451_H_
#define	_TCI29451_H_


#include <asn_application.h>

/* Including external dependencies */
#include "D2945Request.h"
#include "Response.h"
#include "D2945Indication.h"
#include "Exception.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCI29451_PR {
	TCI29451_PR_NOTHING,	/* No components present */
	TCI29451_PR_request,
	TCI29451_PR_response,
	TCI29451_PR_indication,
	TCI29451_PR_exception
	/* Extensions may appear below */
	
} TCI29451_PR;

/* TCI29451 */
typedef struct TCI29451 {
	TCI29451_PR present;
	union TCI29451_u {
		D2945Request_t	 request;
		Response_t	 response;
		D2945Indication_t	 indication;
		Exception_t	 exception;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCI29451_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCI29451;
extern asn_CHOICE_specifics_t asn_SPC_TCI29451_specs_1;
extern asn_TYPE_member_t asn_MBR_TCI29451_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TCI29451_H_ */
#include <asn_internal.h>
