/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-80211"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TCI80211_H_
#define	_TCI80211_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Dot11Request.h"
#include "Response.h"
#include "Dot11Indication.h"
#include "Exception.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCI80211_PR {
	TCI80211_PR_NOTHING,	/* No components present */
	TCI80211_PR_request,
	TCI80211_PR_response,
	TCI80211_PR_indication,
	TCI80211_PR_exception
	/* Extensions may appear below */
	
} TCI80211_PR;

/* TCI80211 */
typedef struct TCI80211 {
	TCI80211_PR present;
	union TCI80211_u {
		Dot11Request_t	 request;
		Response_t	 response;
		Dot11Indication_t	 indication;
		Exception_t	 exception;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCI80211_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCI80211;
extern asn_CHOICE_specifics_t asn_SPC_TCI80211_specs_1;
extern asn_TYPE_member_t asn_MBR_TCI80211_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TCI80211_H_ */
#include <asn_internal.h>
