/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-Dispatcher"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TCIMsg_H_
#define	_TCIMsg_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "Time64.h"
#include "Frame.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCIMsg */
typedef struct TCIMsg {
	long	 version;
	Time64_t	 time;
	Frame_t	 frame;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCIMsg_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCIMsg;

#ifdef __cplusplus
}
#endif

#endif	/* _TCIMsg_H_ */
#include <asn_internal.h>
