/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-SutControl"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TCISutControl_H_
#define	_TCISutControl_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SutRequest.h"
#include "Response.h"
#include "SutResponseInfo.h"
#include "Exception.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCISutControl_PR {
	TCISutControl_PR_NOTHING,	/* No components present */
	TCISutControl_PR_request,
	TCISutControl_PR_response,
	TCISutControl_PR_responseInfo,
	TCISutControl_PR_exception
	/* Extensions may appear below */
	
} TCISutControl_PR;

/* TCISutControl */
typedef struct TCISutControl {
	TCISutControl_PR present;
	union TCISutControl_u {
		SutRequest_t	 request;
		Response_t	 response;
		SutResponseInfo_t	 responseInfo;
		Exception_t	 exception;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCISutControl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCISutControl;
extern asn_CHOICE_specifics_t asn_SPC_TCISutControl_specs_1;
extern asn_TYPE_member_t asn_MBR_TCISutControl_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TCISutControl_H_ */
#include <asn_internal.h>
