/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_TXpower80211_H_
#define	_TXpower80211_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TXpower80211 */
typedef long	 TXpower80211_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TXpower80211;
asn_struct_free_f TXpower80211_free;
asn_struct_print_f TXpower80211_print;
asn_constr_check_f TXpower80211_constraint;
ber_type_decoder_f TXpower80211_decode_ber;
der_type_encoder_f TXpower80211_encode_der;
xer_type_decoder_f TXpower80211_decode_xer;
xer_type_encoder_f TXpower80211_encode_xer;
oer_type_decoder_f TXpower80211_decode_oer;
oer_type_encoder_f TXpower80211_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _TXpower80211_H_ */
#include <asn_internal.h>
