/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_WaveElementsIncluded_H_
#define	_WaveElementsIncluded_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum WaveElementsIncluded {
	WaveElementsIncluded_transmitPowerUsed	= 0,
	WaveElementsIncluded_twoDLocation	= 1,
	WaveElementsIncluded_threeDLocation	= 2,
	WaveElementsIncluded_advertiserId	= 3,
	WaveElementsIncluded_psc	= 4,
	WaveElementsIncluded_ipv6Address	= 5,
	WaveElementsIncluded_servicePort	= 6,
	WaveElementsIncluded_providerMacAddress	= 7,
	WaveElementsIncluded_edcaParameterSet	= 8,
	WaveElementsIncluded_secondaryDns	= 9,
	WaveElementsIncluded_gatewayMacAddress	= 10,
	WaveElementsIncluded_channelNumber	= 11,
	WaveElementsIncluded_dataRate	= 12,
	WaveElementsIncluded_repeatRate	= 13,
	WaveElementsIncluded_rcpiThreshold	= 14,
	WaveElementsIncluded_wsaCountThreshold	= 15,
	WaveElementsIncluded_channelAccess	= 16,
	WaveElementsIncluded_wsaCountThresholdInt	= 17,
	WaveElementsIncluded_channelLoad	= 18
} e_WaveElementsIncluded;

/* WaveElementsIncluded */
typedef BIT_STRING_t	 WaveElementsIncluded_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WaveElementsIncluded;
asn_struct_free_f WaveElementsIncluded_free;
asn_struct_print_f WaveElementsIncluded_print;
asn_constr_check_f WaveElementsIncluded_constraint;
ber_type_decoder_f WaveElementsIncluded_decode_ber;
der_type_encoder_f WaveElementsIncluded_encode_der;
xer_type_decoder_f WaveElementsIncluded_decode_xer;
xer_type_encoder_f WaveElementsIncluded_encode_xer;
oer_type_decoder_f WaveElementsIncluded_decode_oer;
oer_type_encoder_f WaveElementsIncluded_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _WaveElementsIncluded_H_ */
#include <asn_internal.h>
