/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IEEE-1609-3-WEE"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_WsaCountThreshold_H_
#define	_WsaCountThreshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WsaCountThreshold */
typedef long	 WsaCountThreshold_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WsaCountThreshold;
asn_struct_free_f WsaCountThreshold_free;
asn_struct_print_f WsaCountThreshold_print;
asn_constr_check_f WsaCountThreshold_constraint;
ber_type_decoder_f WsaCountThreshold_decode_ber;
der_type_encoder_f WsaCountThreshold_encode_der;
xer_type_decoder_f WsaCountThreshold_decode_xer;
xer_type_encoder_f WsaCountThreshold_encode_xer;
oer_type_decoder_f WsaCountThreshold_decode_oer;
oer_type_encoder_f WsaCountThreshold_encode_oer;

#ifdef __cplusplus
}
#endif

#endif	/* _WsaCountThreshold_H_ */
#include <asn_internal.h>
