/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_WsmChannelOptions_H_
#define	_WsmChannelOptions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServiceInfoExts;

/* WsmChannelOptions */
typedef struct WsmChannelOptions {
	struct ServiceInfoExts	*extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WsmChannelOptions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WsmChannelOptions;
extern asn_SEQUENCE_specifics_t asn_SPC_WsmChannelOptions_specs_1;
extern asn_TYPE_member_t asn_MBR_WsmChannelOptions_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ServiceInfoExts.h"

#endif	/* _WsmChannelOptions_H_ */
#include <asn_internal.h>
