/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_WsmParameters_H_
#define	_WsmParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Psid.h"
#include "RadioInterface.h"
#include <NativeInteger.h>
#include "ChannelNumber80211.h"
#include "DataRate80211.h"
#include "TXpower80211.h"
#include "MACaddress.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* WsmParameters */
typedef struct WsmParameters {
	Psid_t	 psid;
	RadioInterface_t	 radio;
	long	 wsmpVersion;
	ChannelNumber80211_t	 channelIdentifier;
	DataRate80211_t	 dataRate;
	TXpower80211_t	 receivePowerLevel;
	MACaddress_t	 sourceMACAddr;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WsmParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WsmParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_WsmParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_WsmParameters_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _WsmParameters_H_ */
#include <asn_internal.h>
