/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-indication"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#include "WsmParameters.h"

static int
memb_radio_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_wsmpVersion_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_radio_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_oer_constraints_t asn_OER_memb_wsmpVersion_constr_4 CC_NOTUSED = {
	{ 1, 1 }	/* (0..15) */,
	-1};
asn_TYPE_member_t asn_MBR_WsmParameters_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, psid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Psid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"psid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, radio),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RadioInterface,
		0,
		{ &asn_OER_memb_radio_constr_3, 0,  memb_radio_constraint_1 },
		0, 0, /* No default value */
		"radio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, wsmpVersion),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_wsmpVersion_constr_4, 0,  memb_wsmpVersion_constraint_1 },
		0, 0, /* No default value */
		"wsmpVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, channelIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChannelNumber80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, dataRate),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataRate80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, receivePowerLevel),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TXpower80211,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"receivePowerLevel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct WsmParameters, sourceMACAddr),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MACaddress,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sourceMACAddr"
		},
};
static const ber_tlv_tag_t asn_DEF_WsmParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_WsmParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* psid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* radio */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* wsmpVersion */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* channelIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* dataRate */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* receivePowerLevel */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* sourceMACAddr */
};
asn_SEQUENCE_specifics_t asn_SPC_WsmParameters_specs_1 = {
	sizeof(struct WsmParameters),
	offsetof(struct WsmParameters, _asn_ctx),
	asn_MAP_WsmParameters_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_WsmParameters = {
	"WsmParameters",
	"WsmParameters",
	&asn_OP_SEQUENCE,
	asn_DEF_WsmParameters_tags_1,
	sizeof(asn_DEF_WsmParameters_tags_1)
		/sizeof(asn_DEF_WsmParameters_tags_1[0]), /* 1 */
	asn_DEF_WsmParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_WsmParameters_tags_1)
		/sizeof(asn_DEF_WsmParameters_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_WsmParameters_1,
	7,	/* Elements count */
	&asn_SPC_WsmParameters_specs_1	/* Additional specs */
};

