/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCI-wsm"
 * 	found in "TCI.asn1"
 * 	`asn1c -no-gen-PER -fcompound-names -fwide-types`
 */

#ifndef	_WsmServiceInfos_H_
#define	_WsmServiceInfos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WsmServiceInfo;

/* WsmServiceInfos */
typedef struct WsmServiceInfos {
	A_SEQUENCE_OF(struct WsmServiceInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WsmServiceInfos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WsmServiceInfos;
extern asn_SET_OF_specifics_t asn_SPC_WsmServiceInfos_specs_1;
extern asn_TYPE_member_t asn_MBR_WsmServiceInfos_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WsmServiceInfo.h"

#endif	/* _WsmServiceInfos_H_ */
#include <asn_internal.h>
